### PR TITLE
Document interfaces of functions in sorting.cpp

### PR DESCRIPTION
**Pull request by reikdas**

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
Maybe "special" should be "skip_implementation"? It's always good when option/parameter names are specific to what they actually do.

Other than that, looks good. **Could you attach a screenshot of what the sorting-kernel documentation looks like?** I think there should be some message (maybe italicized and parenthesized) about the lack of a normative implementation in Python, so that it doesn't look like a mistake.

These might be functions whose normative definition is written by hand. It's pretty easy to replace the C++ standard library sort functions with Python standard library sort functions. It wouldn't be the same sorting algorithm, but performance (even "big O" time) is not part of the definitions of these functions. There would be visible differences in how the unstable sort deals with equal values (visible in argsort), and possibly also a difference in the stable sort's "stability policy." The tests shouldn't be sensitive to this.

But since this would have to be manual, we should avoid developing tests for the sorting part until the other parts are done. That will reveal issues in how to generalize the automated testing.

**Comment by reikdas** [comment]
Some screenshots - 
image
image

What do you think?

I wanted to use Black to format the code I wrote by hand for the kernels in sorting.cpp (similar to the generated Python translations of kernels) but there was a weird indentation error I was unable to handle :(

**Comment by jpivarski** [comment]
These are looking good. I didn't realize that you'd try manual conversions, but that's good because it will eventually be needed. Eventually, hard-coded Python will be the normative definitions; most of these normative definitions will come from automatic conversions before being hard-coded, but the sorting ones will be hard-coded by hand.

Since you have manually written Python for the sorting kernels, you'll be able to include them in your tests and work out the bugs that way. That will be a good test, having both automatically converted kernels and manually written kernels—each would catch errors the other doesn't.

About formatting with Black; please do, for consistency and to avoid scrolling in the window. Black formatting has forced me to use fewer list comprehensions because comprehensions that would make the code easier to read and clearer on a long line make the code harder to read and more obscure with Black's indentation policies. As such, I usually rewrite list comprehensions into regular for loops if Black makes a mess of them. That might also make the Python more beginner-friendly because list comprehensions are an intermediate topic. (What I don't like is how everything gets longer, stretched vertically—vertical screen space is a limited quantity, too! But oh well, it's how things are being done these days.)

Let me know when you're done with the PR and I'll merge it. I like the screenshots. Maybe you want to say that the code samples you've written are "not normative," rather than "not accurate." At the moment, we're doing dry runs of building up a normative specification.

**Comment by reikdas** [comment]
The PR should be done now.

**Pull request merged**
