### PR TITLE
fix: distributed rdataframe is not yet support

### LINKED ISSUE #3061: from_rdataframe does not work for distributed rdataframe
### Version of Awkward Array

2.6.2

### Description and code to reproduce

For distributed RDataFrames, e.g. with dask or spark backends, some operations are not exposed including `GetColumnType` which is used by the `ak.from_rdataframe` method.

Reproducer:
```
import ROOT
import awkward as ak
from dask.distributed import LocalCluster, Client

RDataFrame = ROOT.RDF.Experimental.Distributed.Dask.RDataFrame

cluster = LocalCluster(n_workers=4, threads_per_worker=1, processes=True)
client = Client(cluster)
rdf = RDataFrame(1000, daskclient=client).Define("x", "1")

array = ak.from_rdataframe(rdf, columns=['x'])
```

which gives the error:

```
AttributeError: 'Define' object has no attribute 'GetColumnType'

This error occurred while calling

    ak.from_rdataframe(
        NodeProxy-instance
        columns = ['x']
    )
```

One way to solve this will be to access the `GetColumnType` method internally (this is not ideal, an [issue ](https://github.com/root-project/root/issues/15039)is submitted to ROOT github):
```
rdf._headnode._localdf.GetColumnType
```

### PR DESCRIPTION
**Pull request by ianna**
add a clear message

### CODE REVIEW

**Comment by ianna** [comment]
@jpivarski - is someone looking into pypy segfaults? Thanks

**Comment by jpivarski** [comment]
> @jpivarski - is someone looking into pypy segfaults? Thanks

Not at the moment. If you have a chance to look into #2971, that would be great.

**Review by ianna — COMMENTED** [review]
@jpivarski - as discussed yesterday we are making it clear that distributed RDataFrame is not supported yet.

**Review by jpivarski — APPROVED** [review]
If only distributed RDataFrames have the `proxied_node` attribute, this is a good way to catch it. It sounds like that might be true, but would checking the data type be more robust? E.g.

```python
if type(data_frame).__name__ == "DistributedRDataFrame":
```

or something similar?

Either way, this is good to merge. I'll let you decide how to handle it.

**Pull request merged**
