### PR TITLE
Fix Windows wheel and add auditwheel.

### LINKED ISSUE #141: Windows wheel puts _io*.pyd, layout*.pyd, and types*.pyd at root level.
This structure is wrong:

```
.
├── awkward1
│   ├── _autograd.py
│   ├── awkward-cpu-kernels.dll
│   ├── awkward-cpu-kernels.exp
│   ├── awkward-cpu-kernels.lib
│   ├── awkward-cpu-kernels-static.lib
│   ├── awkward.dll
│   ├── awkward.exp
│   ├── awkward.lib
│   ├── awkward-static.lib
│   ├── behaviors
│   │   ├── __init__.py
│   │   └── string.py
│   ├── _cpu_kernels.py
│   ├── highlevel.py
│   ├── __init__.py
│   ├── _io.cp37-win32.pyd
│   ├── layout.cp37-win32.pyd
│   ├── _libawkward.py
│   ├── _numba
│   │   ├── arrayview.py
│   │   ├── builder.py
│   │   ├── __init__.py
│   │   └── layout.py
│   ├── numba.py
│   ├── _numexpr.py
│   ├── _numpy.py
│   ├── operations
│   │   ├── convert.py
│   │   ├── describe.py
│   │   ├── __init__.py
│   │   ├── reducers.py
│   │   └── structure.py
│   ├── _pandas.py
│   ├── types.cp37-win32.pyd
│   └── _util.py
├── awkward1-0.1.138.data
│   └── data
│       └── include
│           └── awkward
│               ├── array
│               │   ├── EmptyArray.h
│               │   ├── IndexedArray.h
│               │   ├── ListArray.h
│               │   ├── ListOffsetArray.h
│               │   ├── None.h
│               │   ├── NumpyArray.h
│               │   ├── RawArray.h
│               │   ├── RecordArray.h
│               │   ├── Record.h
│               │   ├── RegularArray.h
│               │   └── UnionArray.h
│               ├── builder
│               │   ├── ArrayBuilder.h
│               │   ├── ArrayBuilderOptions.h
│               │   ├── BoolBuilder.h
│               │   ├── Builder.h
│               │   ├── Float64Builder.h
│               │   ├── GrowableBuffer.h
│               │   ├── IndexedBuilder.h
│               │   ├── Int64Builder.h
│               │   ├── ListBuilder.h
│               │   ├── OptionBuilder.h
│               │   ├── RecordBuilder.h
│               │   ├── StringBuilder.h
│               │   ├── TupleBuilder.h
│               │   ├── UnionBuilder.h
│               │   └── UnknownBuilder.h
│               ├── Content.h
│               ├── cpu-kernels
│               │   ├── getitem.h
│               │   ├── identities.h
│               │   ├── operations.h
│               │   ├── reducers.h
│               │   └── util.h
│               ├── Identities.h
│               ├── Index.h
│               ├── io
│               │   ├── json.h
│               │   └── root.h
│               ├── Iterator.h
│               ├── python
│               │   ├── content.h
│               │   ├── identities.h
│               │   ├── index.h
│               │   └── util.h
│               ├── Reducer.h
│               ├── Slice.h
│               ├── type
│               │   ├── ArrayType.h
│               │   ├── ListType.h
│               │   ├── OptionType.h
│               │   ├── PrimitiveType.h
│               │   ├── RecordType.h
│               │   ├── RegularType.h
│               │   ├── Type.h
│               │   ├── UnionType.h
│               │   └── UnknownType.h
│               └── util.h
├── awkward1-0.1.138.dist-info
│   ├── entry_points.txt
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── top_level.txt
│   └── WHEEL
├── _io.cp37-win32.pyd
├── layout.cp37-win32.pyd
└── types.cp37-win32.pyd
```

because the three extension modules are both in the Python package _and_ at site-packages root. This would allow `import layout` in addition to `import awkward1.layout`. Worse yet, `import types` might shadow the standard library module!

This needs to be fixed before we get any Windows users.

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
@henryiii Since it looks like you're not working on this branch at the moment, I'm going to use it to try to fix the Windows part. That seems to be orthogonal to what you're doing. I'll be temporarily turning off all deployment builds except Windows, so we probably can't work on it at the same time. Let me know if this affects your plans.

**Comment by henryiii** [comment]
I think I nearly had it, fixed the one mistake, so macOS and Linux should work when they come back on.

(Sorry, forgot to skip ci!)

**Comment by henryiii** [comment]
Because you are using your own personal Azure instead of the Scikit-HEP one, I can't cancel the build. Feel free to do so.

**Comment by jpivarski** [comment]
@henryiii I'm done with WOWW. Anything more that you want to do with the PR is up to you; let me know when I should merge it.

I'd prefer to use the Scikit-HEP Azure. That's another thing that we should switch over to. Not today, though.

**Comment by henryiii** [comment]
After tests pass (are they running?), if you could trigger a deploy just to make sure everything works and so I can see what the output of the `auditwheel show` is, that should be great.

**Comment by jpivarski** [comment]
I think the tests are waiting on Yana's "final cleanup" in PR #132 to finish. Just a minute or two...

**Pull request merged**
