### PR TITLE
fix: correct dtypes for numpy v2 

### LINKED ISSUE #3160: np.sum of an array of boolean dtype in tests/test_0115_generic_reducer_operation.py
### Version of Awkward Array

2.6.4 (master branch)

### Description and code to reproduce

According to Numpy documentation:

```
dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signed then the platform integer
        is used while if `a` is unsigned then an unsigned integer of the
        same precision as the platform integer is used.
```

see https://github.com/numpy/numpy/blob/v2.0.0/numpy/_core/fromnumeric.py#L2255-L2392

```python
================================== FAILURES ===================================
__________________________ test_sumprod_types_FIXME ___________________________

    def test_sumprod_types_FIXME():
        array = np.array([[True, False, False], [True, False, False]])
        content2 = ak.contents.NumpyArray(array.reshape(-1))
        offsets3 = ak.index.Index64(np.array([0, 3, 3, 5, 6], dtype=np.int64))
        depth1 = ak.contents.ListOffsetArray(offsets3, content2)
>       assert (
            np.sum(array, axis=-1).dtype
            == ak.to_numpy(ak.sum(depth1, axis=-1, highlevel=False)).dtype
        )
E       AssertionError: assert dtype('int32') == dtype('int64')
E        +  where dtype('int32') = array([1, 1]).dtype
E        +    where array([1, 1]) = <function sum at 0x046AF640>(array([[ True, False, False],\n       [ True, False, False]]), axis=-1)
E        +      where <function sum at 0x046AF640> = np.sum
E        +  and   dtype('int64') = array([1, 0, 1, 0], dtype=int64).dtype
E        +    where array([1, 0, 1, 0], dtype=int64) = <function to_numpy at 0x052E71D8>(<NumpyArray dtype='int64' len='4'>[1 0 1 0]</NumpyArray>)
E        +      where <function to_numpy at 0x052E71D8> = ak.to_numpy
E        +      and   <NumpyArray dtype='int64' len='4'>[1 0 1 0]</NumpyArray> = <function sum at 0x052C7D60>(<ListOffsetArray len='4'>\n    <offsets><Index dtype='int64' len='5'>\n        [0 3 3 5 6]\n    </Index></offsets>\n    <content><NumpyArray dtype='bool' len='6'>\n        [ True False False  True False False]\n    </NumpyArray></content>\n</ListOffsetArray>, axis=-1, highlevel=False)
E        +        where <function sum at 0x052C7D60> = ak.sum

array      = array([[ True, False, False],
       [ True, False, False]])
content2   = <NumpyArray dtype='bool' len='6'>
    [ True False False  True False False]
</NumpyArray>
depth1     = <ListOffsetArray len='4'>
    <offsets><Index dtype='int64' len='5'>
        [0 3 3 5 6]
    </Index></offsets>
    <content><NumpyArray dtype='bool' len='6'>
        [ True False False  True False False]
    </NumpyArray></content>
</ListOffsetArray>
offsets3   = <Index dtype='int64' len='5'>
    [0 3 3 5 6]
</Index>

tests\test_0115_generic_reducer_operation.py:1414: AssertionError
_____________________________ test_sumprod_types ______________________________

    def test_sumprod_types():
        def prod(xs):
            out = 1
            for x in xs:
                out *= x
            return out
    
        array = np.array([[True, False, False], [True, False, False]])
        content2 = ak.contents.NumpyArray(array.reshape(-1))
        offsets3 = ak.index.Index64(np.array([0, 3, 3, 5, 6], dtype=np.int64))
        depth1 = ak.contents.ListOffsetArray(offsets3, content2)
    
        assert sum(to_list(np.sum(array, axis=-1))) == sum(
            to_list(ak.sum(depth1, axis=-1, highlevel=False))
        )
        assert prod(to_list(np.prod(array, axis=-1))) == prod(
            to_list(ak.prod(depth1, axis=-1, highlevel=False))
        )
    
        array = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.int8)
        content2 = ak.contents.NumpyArray(array.reshape(-1))
        offsets3 = ak.index.Index64(np.array([0, 3, 3, 5, 6], dtype=np.int64))
        depth1 = ak.contents.ListOffsetArray(offsets3, content2)
    
>       assert (
            np.sum(array, axis=-1).dtype
            == ak.to_numpy(ak.sum(depth1, axis=-1, highlevel=False)).dtype
        )
E       AssertionError: assert dtype('int32') == dtype('int64')
E        +  where dtype('int32') = array([ 3, 12]).dtype
E        +    where array([ 3, 12]) = <function sum at 0x046AF640>(array([[0, 1, 2],\n       [3, 4, 5]], dtype=int8), axis=-1)
E        +      where <function sum at 0x046AF640> = np.sum
E        +  and   dtype('int64') = array([3, 0, 7, 5], dtype=int64).dtype
E        +    where array([3, 0, 7, 5], dtype=int64) = <function to_numpy at 0x052E71D8>(<NumpyArray dtype='int64' len='4'>[3 0 7 5]</NumpyArray>)
E        +      where <function to_numpy at 0x052E71D8> = ak.to_numpy
E        +      and   <NumpyArray dtype='int64' len='4'>[3 0 7 5]</NumpyArray> = <function sum at 0x052C7D60>(<ListOffsetArray len='4'>\n    <offsets><Index dtype='int64' len='5'>\n        [0 3 3 5 6]\n    </Index></offsets>\n    <content><NumpyArray dtype='int8' len='6'>[0 1 2 3 4 5]</NumpyArray></content>\n</ListOffsetArray>, axis=-1, highlevel=False)
E        +        where <function sum at 0x052C7D60> = ak.sum

array      = array([[0, 1, 2],
       [3, 4, 5]], dtype=int8)
content2   = <NumpyArray dtype='int8' len='6'>[0 1 2 3 4 5]</NumpyArray>
depth1     = <ListOffsetArray len='4'>
    <offsets><Index dtype='int64' len='5'>
        [0 3 3 5 6]
    </Index></offsets>
    <content><NumpyArray dtype='int8' len='6'>[0 1 2 3 4 5]</NumpyArray></content>
</ListOffsetArray>
offsets3   = <Index dtype='int64' len='5'>
    [0 3 3 5 6]
</Index>
prod       = <function test_sumprod_types.<locals>.prod at 0x044F7C40>

tests\test_0115_generic_reducer_operation.py:1448: AssertionError

```

### PR DESCRIPTION
**Pull request by ianna**
fixes #3160

### CODE REVIEW

**Review by ianna — COMMENTED** [review]
@jpivarski - this PR fixes the issue with Numpy v2: typically, `np.intp` is used to represent the platform integer type and the check for fallback on it is valid only for `Numpy` version 2 and higher.

**Review by jpivarski — CHANGES_REQUESTED** [review]
Great! Thanks for finding and fixing this. However, it's not fully testing the platform-version combinations users might have. The

https://github.com/scikit-hep/awkward/blob/02858f895f89f7e6292dc3a8d7e079d596885286/.github/workflows/test.yml#L52-L54

test _used to_ check 32-bit Windows with NumPy < 2, now it tests 32-bit Windows with NumPy ≥ 2. However, nothing tests 32-bit Windows with NumPy < 2 anymore, and we need to be sure that the `_use32` evaluates to the right boolean value for all of those cases. This test should be split into two tests; one for NumPy < 2, one for NumPy ≥ 2, and both for 32-bit Windows.

While adding that 1 new test, these 3 old tests can be _removed_:

https://github.com/scikit-hep/awkward/blob/02858f895f89f7e6292dc3a8d7e079d596885286/.github/workflows/test.yml#L64-L75

which implies that we can also delete this file:

https://github.com/scikit-hep/awkward/blob/main/requirements-test-numpy2.txt

When those tests are changed, I'll have to update the set of required tests, but just request a review again. (These are all adjusting for the fact that NumPy has been officially released.)

**Comment by ianna** [comment]
@jpivarski - please, update required tests. Thanks!

**Review by jpivarski — APPROVED** [review]
At first, I thought that "Tests / Run Tests (pypy3.9, x64, ubuntu-latest, pypy)" was another new test, since it's not required yet, either. But now I remember that it's there so we can keep an eye on it, not so that we can promise that Awkward works on PyPy. (We don't provide a wheel for that.)

So, this gets us entirely up-to-date with NumPy 2.0 in its fully released state. This is ready to merge into `main`, and it can fix #3136 when that is subsequently synced with `main`.

**Pull request merged**
