### PR TITLE
add int64_t definition for Windows

### PR DESCRIPTION
**Pull request by ianna**

### CODE REVIEW

**Comment by ianna** [comment]
@ManasviGoyal - could you please test that it works for you. Thanks

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal - could you please test that it works for you. Thanks

Hi @ianna. I have already made a PR for this issue. Please refer - #1571

**Comment by ianna** [comment]
> > @ManasviGoyal - could you please test that it works for you. Thanks
> 
> Hi @ianna. I have already made a PR for this issue. Please refer - #1571

Yes, I guess we got our wires crossed :-)
I think, we use `stdint.h` (as in this PR) everywhere else, not `cstdint`. Please, let me know if this PR fixes the problem for you. Thanks.

**Comment by ManasviGoyal** [comment]
> > > @ManasviGoyal - could you please test that it works for you. Thanks
> > 
> > 
> > Hi @ianna. I have already made a PR for this issue. Please refer - #1571
> 
> Yes, I guess we got our wires crossed :-) I think, we use `stdint.h` (as in this PR) everywhere else, not `cstdint`. Please, let me know if this PR fixes the problem for you. Thanks.

Okay sure.

Yes it works. But I don't think we need too include it in all the files. Only adding it in `BuilderOptions.h` works.

Also, please cherry pick the 2nd comment from my PR. I have fixed the builder names to make them uniform throughout the tests.

**Comment by ianna** [comment]
> > > > @ManasviGoyal - could you please test that it works for you. Thanks
> > > 
> > > 
> > > Hi @ianna. I have already made a PR for this issue. Please refer - #1571
> > 
> > 
> > Yes, I guess we got our wires crossed :-) I think, we use `stdint.h` (as in this PR) everywhere else, not `cstdint`. Please, let me know if this PR fixes the problem for you. Thanks.
> 
> Okay sure.
> 
> Yes it works. But I don't think we need too include it in all the files. Only adding it in `BuilderOptions.h` works.
> 

all the files need it because they use `int64_t` and should not rely on other includes that include this one :-)
 
> Also, please cherry pick the 2nd comment from my PR. I have fixed the builder names to make them uniform throughout the tests.

I think, this one can be a part of your documentation PR. I'm sure there will be more fixes. Thanks!

**Review by jpivarski — APPROVED** [review]
This is definitely an improvement. Windows is demonstrating the fact that we were relying on stdint.h without asking for it (we got it implicitly through one of the other imports).

This can be (squash-and-) merged whenever you feel you're done with it!

**Pull request merged**
