### PR TITLE
libawkward: fix vtable regressions

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Comment by jpivarski** [comment]
The errors are in new code: VirtualArray didn't exist when you last worked on this:

```
  In file included from /Users/runner/runners/2.166.4/work/1/s/src/libawkward/array/VirtualArray.cpp:9:
  In file included from /Users/runner/runners/2.166.4/work/1/s/include/awkward/array/VirtualArray.h:13:
  /Users/runner/runners/2.166.4/work/1/s/include/awkward/virtual/ArrayGenerator.h:20:23: error: 'ArrayGenerator' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
    class EXPORT_SYMBOL ArrayGenerator {
                        ^
  /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4331:26: note: in instantiation of function template specialization 'std::__1::__shared_ptr_emplace<awkward::SliceGenerator, std::__1::allocator<awkward::SliceGenerator> >::__shared_ptr_emplace<const std::__1::shared_ptr<awkward::Form>, long long, const std::__1::shared_ptr<awkward::ArrayGenerator> &, awkward::Slice &>' requested here
      ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                           ^
  /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4710:29: note: in instantiation of function template specialization 'std::__1::shared_ptr<awkward::SliceGenerator>::make_shared<const std::__1::shared_ptr<awkward::Form>, long long, const std::__1::shared_ptr<awkward::ArrayGenerator> &, awkward::Slice &>' requested here
      return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                              ^
  /Users/runner/runners/2.166.4/work/1/s/src/libawkward/array/VirtualArray.cpp:440:40: note: in instantiation of function template specialization 'std::__1::make_shared<awkward::SliceGenerator, const std::__1::shared_ptr<awkward::Form>, long long, const std::__1::shared_ptr<awkward::ArrayGenerator> &, awkward::Slice &>' requested here
      ArrayGeneratorPtr generator = std::make_shared<SliceGenerator>(
                                         ^
  1 error generated.
  make[2]: *** [CMakeFiles/awkward-objects.dir/src/libawkward/array/VirtualArray.cpp.o] Error 1
```

The warnings about overriding are also new and easily fixed. I fixed that one in another branch so you can safely ignore it. It's the warning about VirtualArray that matters.

I don't know what is different about VirtualArray; I think it has the same mix of pure virtual and concrete methods.

**Comment by veprbl** [comment]
> VirtualArray didn't exist when you last worked on this

That's not the issue. The issue is that Apple's toolchain identifies as AppleClang, so you were working without tests.

**Comment by jpivarski** [comment]
@veprbl I wasn't sure if you were done, so I was waiting to see what happens. Is this PR done? It passed all the tests when you last worked on it, and I can merge with master to see if it's still okay. If the answer to both questions is "yes," then I'll merge it.

Thanks!

**Comment by veprbl** [comment]
@jpivarski This is ready, I believe.

**Pull request merged**
