### PR TITLE
User Guide of LayoutBuilder

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Working on the user guide of Layout Builder

### CODE REVIEW

**Comment by agoose77** [comment]
Hi @ManasviGoyal, are we also planning on exposing LayoutBuilder to Python (e.g. via cppyy)? I have seen that Jim's indicated that `LayoutBuilder` is not important in Python contexts, implying that the answer is no, but I'm curious to know if that thought process has changed.

In general the Doxygen docs won't require any changes. In #1563, I've moved the Doxygen URL, but you don't need to touch Sphinx in order to build the C++ docs.

The user-guide *has* moved around a lot compared to `main`; the JupyterBook documentation has been integrated directly into the Sphinx documentation. 

If you can, I'd prefer it if you based this PR on #1563. I'm hoping that it will be mergeable shortly. The changes that I make after #1563 will be smaller, so we shouldn't have too many merge conflicts. Otherwise, I'll need to do a small amount of work to rebase the docs branch on main after your changes!

**Comment by ManasviGoyal** [comment]
> Hi @ManasviGoyal, are we also planning on exposing LayoutBuilder to Python (e.g. via cppyy)? I have seen that Jim's indicated that `LayoutBuilder` is not important in Python contexts, implying that the answer is no, but I'm curious to know if that thought process has changed.
> 
> In general the Doxygen docs won't require any changes. In #1563, I've moved the Doxygen URL, but you don't need to touch Sphinx in order to build the C++ docs.
> 
> The user-guide _has_ moved around a lot compared to `main`; the JupyterBook documentation has been integrated directly into the Sphinx documentation.
> 
> If you can, I'd prefer it if you based this PR on #1563. I'm hoping that it will be mergeable shortly. The changes that I make after #1563 will be smaller, so we shouldn't have too many merge conflicts. Otherwise, I'll need to do a small amount of work to rebase the docs branch on main after your changes!

Hi. Sure I can rebase this PR.

For now, we are not planning it to expose it to Python (though it will be used in RDataFrame for JIT Complilation (via cppyy), @ianna is working on that).

So, for doxygen, I can directly add the comments in the files like I have done. No other thing is required, right?

Also, for the `user-guide` where should I place it for now?

**Comment by agoose77** [comment]
You're right about the C++ - nothing has changed there!

Concerning the user guide, this now lives in `docs-sphinx/user-guide`. The contents of these docs haven't changed much, but the way that you build them has. We no longer use `jupyter-book` to build our books. It's still the same components (like `mystnb`), but now we directly use Sphinx. 

If you want to preview the docs locally:
1. `cd` to `docs-sphinx` 
2. install the requirements with `pip install -r requirements.txt`
3. comment / delete [the subprocesses](https://github.com/scikit-hep/awkward/blob/a75262abdf3d17fab118828fd2f6eafca0e911fa/docs-sphinx/conf.py#L118-L129) that currently run on every `sphinx-build` invocation. This is just to make your build faster. It means that Python API docs, release notes, and C++ docs, won't be generated. If you want to update the doxygen docs, you can leave the Doxygen lines untouched.
4. run `sphinx-build . _build` to perform a full build

If you're only changing a few files during development, you can limit Sphinx to update only a subset of files with `sphinx-build . _build file-1.md ...`

In addition to rebasing on https://github.com/scikit-hep/awkward/branches/docs-phase-2, could you also change the merge target of this PR to the `docs` branch? 

image

Off the top of my head, the user guide will be an interesting opportunity to use a notebook to demonstrate LayoutBuilder, and how to use it to build an `ak.Array`.

If we just want to test that our documented code works with released Awkward versions, we could use the `xeus-cling` Jupyter kernel with jupyter-book. This will run C++ code contained in `:::{code-cell}` MyST directives under Jupyter (e.g. https://raw.githubusercontent.com/scikit-hep/awkward/docs-phase-2/docs-sphinx/user-guide/how-to-convert-pandas.md)

However, we could also use  `cppyy` to both test `LayoutBuilder`, and also show how to wrap it with `ak.from_buffers`. This might be a reasonable amount of work, so feel free to discuss it with Jim in case it's out of scope for your project!

**Comment by jpivarski** [comment]
I think that this was a draft PR for so long that it got mangled by @agoose77's documentation updates.

Since the goal of this PR is to write a user guide, maybe the easiest way to do it is to close this PR and provide @agoose77 with a markdown version of the user guide, and he'll integrate it with the new documentation?

I searched through this PR's changelog and didn't see what looked like a markdown user guide for LayoutBuilder. Did I miss it?

**Comment by ManasviGoyal** [comment]
> I think that this was a draft PR for so long that it got mangled by @agoose77's documentation updates.
> 
> Since the goal of this PR is to write a user guide, maybe the easiest way to do it is to close this PR and provide @agoose77 with a markdown version of the user guide, and he'll integrate it with the new documentation?
> 
> I searched through this PR's changelog and didn't see what looked like a markdown user guide for LayoutBuilder. Did I miss it?

Hi. Sorry, I haven't been well since past 2 weeks. So, had to pause it midway. This PR is not updated that's why the markdown file is missing.

I planned on closing this PR and opening a new one with the Markdown file since there have been changes in the documentation. I still have to add a few things. I'll update and get it reviewed by @agoose77 so that he can integrate it. 

Closing this one. Thanks.

**Pull request closed without merging**
