### PR TITLE
docs: fix redirects

### LINKED ISSUE #1808: URL mapping in new docs
### Which documentation?

Tutorials site

### What needs to be documented?

https://github.com/scikit-hep/uproot5/issues/760 points out a dead link in the Uproot docs:

https://awkward-array.readthedocs.io/en/latest/ak.types.Type.html

That's an indication that this link used to work and it has probably been shared beyond just the Uproot docs. It doesn't have the `_auto` in the URL because it was one of the hand-written reST files, not one made by `prepare_docstrings.py`.

Looking in the `docs` branch by swapping `latest` with `docs`, it still doesn't exist, but

https://awkward-array.readthedocs.io/en/docs/reference/generated/ak.types.Type.html

does exist, and it's where this URL is supposed to go. So we'll need a redirect.

Also, the layout URLs that are now

https://awkward-array.readthedocs.io/en/docs/reference/generated/ak.contents.Content.html

(unfortunately!) need a redirect from "`ak.layout.`" to "`ak.contents.`" (all the Content classes). Similarly for "`ak.layout.Record`" (only one Record) → "`ak.record.Record`" and "`ak.layout.Index`" → "`ak.index.Index`" (all the Index classes). Unless we want those links to fail as an indicator to users that the name no longer exists? Maybe better, a page briefly describing the name change (rather than an automated redirect)?

### PR DESCRIPTION
**Pull request by agoose77**
This PR fixes the redirects that map old v1 URLs onto v2.

----
:books: The documentation for this PR will be available at <https://awkward-array.readthedocs.io/en/agoose77-docs-fix-url-redirects/> once Read the Docs has finished building :hammer:

### CODE REVIEW

**Comment by jpivarski** [comment]
Fixes scikit-hep/uproot5#760

**Review by jpivarski — APPROVED** [review]
The great thing about this is that I could directly test it. I tried all of the old links, substituting `latest` → `agoose77-docs-fix-url-redirects`, and they all work now.

I'll enable auto-merge.

**Comment by agoose77** [comment]
I think that might already have been fixed by making `latest` point to `main-v1` on RTD? The `latest` branch is still v1.

**Comment by jpivarski** [comment]
Or not. This doesn't trigger the build tests. But the docs tests have all completed successfully, and my test of the links does what an integration test would do.

**Comment by agoose77** [comment]
Don't merge just yet - noticed a link misbehaving

**Comment by jpivarski** [comment]
Okay, I won't.

**Comment by agoose77** [comment]
OK, seems fine!

**Comment by jpivarski** [comment]
For instance, this was the originally reported dead link:

* https://awkward-array.readthedocs.io/en/latest/ak.types.Type.html

(which is live now, but v1, as it should be).

What I tested was:

* https://awkward-array.readthedocs.io/en/agoose77-docs-fix-url-redirects/ak.types.Type.html

and similar for all `layout` → `index`, `record`, `contents`; even `ak.layout.ArrayBuilder` went to the right place.

I've approved this; when you're done with the change you want to make, you can merge it.

**Pull request merged**
