### PR TITLE
Continue from #224: fromarrow and toarrow.

### LINKED ISSUE #68: toarrow and fromarrow
Similar to the [Awkward ↔ Arrow conversions in Awkward0](https://github.com/scikit-hep/awkward-array/blob/master/awkward/arrow.py), except in C++, rather than Python.

It's a recursive if-elseif-elseif-...-else chain down the list of array node types, replacing each from one library with its equivalent in the other. Conversions from Arrow → Awkward can be zero-copy, now that BitMaskedArray exists, and conversions from Awkward → Arrow would involve one copy (to move the disparate buffers into Arrow's single buffer format).

### PR DESCRIPTION
**Pull request by jpivarski**
99.5% of the work on this PR was done by @trickarcher. I tried using GitHub's "check out locally" and followed instructions, but it won't let me commit back to his repo and get it all done under one PR. So I have to close his and open a new PR to put my last touch-ups on it, but most of the work is his.

### CODE REVIEW

**Comment by trickarcher** [comment]
Thank you so much for this! @jpivarski, I never knew there were so many things hidden away. I'll write better test suites from now on! Thanks again!

**Comment by jpivarski** [comment]
Don't worry about it—I don't think these issues could have been solved by "more diligence." There's just a lot of things that need to be considered and it will take time to get them all in the documentation.

One thing that none of these tests would have triggered, including the ones I ported over from old Awkward, is that contents can be longer than the enclosing container needs it to be (e.g. a ListOffsetArray might have "10" as `offsets[-1]`, but its `content` can have a length that is longer than 10). This is valid in Awkward Array, though rare and not included in any tests, but I don't think it's valid in Arrow. So when `to_arrow` goes down to the next level with `recurse`, I've just added a slice of the content so that it's exactly the right length, all the way down. This is an example of where 100% test coverage fails: even though the tests now have 100% coverage, they would not have caught this.

**Comment by trickarcher** [comment]
Wow yeah, I never tested it out with that possibility. However, strangely enough, I did catch this issue during the `to_arrow` conversion of `ByteMaskedArray`. So beyond the masks, the content array was copied `as-is`, which was not what `awkward-1.0` was doing. `awkward-1.0` stopped when the masks ran out of indices to apply masks on. So I just sliced them after the entire conversion was done.
Also, are we testing the conversions out with some large dataset?

**Comment by jpivarski** [comment]
> Also, are we testing the conversions out with some large dataset?

I don't have plans to do so, but it wouldn't be a bad idea. However, @kyungeonchoi might end up doing this as part of ssl-hep/ServiceX#131. That will involve large datasets pretty soon.

**Comment by trickarcher** [comment]
Yup, makes sense. Thanks!

**Pull request merged**
