### PR TITLE
test: generate unit tests for cpu and cuda

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Generated `unit-tests` for `cpu-kernels` (4978 tests which run in the CI too) and `cuda-kernels`. For now, I have added a `status` in the `kernel-test-data.json` to turn off the cuda tests. As I will fix/add the kernels, I will turn the tests for the kernels on.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
This is good! It adds the tests that you need, you can toggle them with `status`, I just checked it out and tried them (all good), and I see that they're running in CI.

This can be merged; do so whenever you're ready!

**Comment by jpivarski** [comment]
Oh, one other thing: you'll want to include these new directories in `.gitignore`.

Don't merge yet—I'll add them.

**Comment by jpivarski** [comment]
Okay, now it can be merged, when you're ready.

**Comment by ManasviGoyal** [comment]
> Oh, one other thing: you'll want to include these new directories in `.gitignore`.
> 
> Don't merge yet—I'll add them.

There is another `.gitignore` in the `awkward-cpp` where all the `cpu` tests are being ignored. I'll remove them from there since it is redundant.

**Comment by jpivarski** [comment]
> There is another `.gitignore` in the `awkward-cpp` where all the `cpu` tests are being ignored. I'll remove them from there since it is redundant.

Thanks!

**Pull request merged**
