### PR TITLE
feat: add `to_raggedtensor` and `from_raggedtensor`

### LINKED ISSUE #1466: New to/from_raggedtensor and to/from_nestedtensor functions
### Description of new feature

TensorFlow's RaggedTensor has been around for a while and PyTorch's NestedTensor is new, but they should be conversion targets for Awkward Arrays. And then a tutorial should be written in the spirit of this one:

https://www.tensorflow.org/text/tutorials/text_generation

but using Awkward strings ↔ RaggedTensors instead of making `np.array(["...", "...", ...], dtype=object)`. It's a great example of why that interface would be useful, particularly when paired with `ak.str.*` functions. (We can demonstrate the difference with a scaling test on some enormous dataset. What's an enormous text dataset? I wonder...)

I believe that this is an equivalent for PyTorch's NestedTensor:

https://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html

I don't know if JAX has a ragged array interface, but if it does, let's get that, too. All of these converters are relatively easy, but we'd have to get TensorFlow, PyTorch, and JAX into at least one of the CI tests. TensorFlow and JAX can be hard to install.

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #1466

### CODE REVIEW

**Comment by agoose77** [comment]
@jpivarski do we want to support converting unused optiontype layouts into RaggedTensors? (where `UnmaskedArray` is a perfect example of "unused optiontype")?

I'm currently leaning into "no", or "not silently" (require a flag to allow unused options).

BTW, we can discuss this tomorrow, I'm just getting it down on GH now.

**Comment by jpivarski** [comment]
I don't think RaggedTensors can allow for missing values. However, if the policy is to turn missing numbers into `np.nan` and missing lists into empty lists, then UnmaskedArrays would just go away.

I think it would be desirable to do that, considering how many missing values come out of Parquet files and Arrow. (And Awkward Array might become the go-between from a Parquet/Arrow source to machine learning.)

**Comment by agoose77** [comment]
> I think it would be desirable to do that, considering how many missing values come out of Parquet files and Arrow. (And Awkward Array might become the go-between from a Parquet/Arrow source to machine learning.)

Counterpoint - we already have `fill_none` et al. to let users do this. Should we keep `to_raggedtensor` simple by requiring users to convert their data first? That way, they also are required to think about what their data should look like after the transformation.

Additionally, I'm not sure how useful `nan` is in a context of ML (for which I'm referrring to TensorFlow's main use case)?

(I'm generally uneasy about making it easier to ignore whether an array has an option, mainly because they can significantly affect the interpretation of the array, and proliferate easily between array transformations.)

I'm leaning into whatever your final take on this is, so let me know ;) We can discuss tomorrow.

**Comment by agoose77** [comment]
As discussed in my weekly meeting, we should just convert `None` to `np.nan` so that the burden is placed on the user in the tensorflow space. There are routines to subsequently convert these values to meaningful results.

**Comment by agoose77** [comment]
This will need rebasing, so I'll close it for now.

**Pull request closed without merging**
