### PR TITLE
C++ refactoring: 'simplify_uniontype' only in UnionArray

### PR DESCRIPTION
**Pull request by ioanaif**

### CODE REVIEW

**Comment by jpivarski** [comment]
So far, this _removes_ `simplify_uniontype`, but it doesn't move it into UnionArray.

**Comment by ioanaif** [comment]
> So far, this _removes_ `simplify_uniontype`, but it doesn't move it into UnionArray.

It was already in UnionArray, so I just removed it from `content`.

**Comment by jpivarski** [comment]
Okay, so is this PR done?

**Comment by ioanaif** [comment]
Yes. All done with this PR. Will open new ones for the other tickets starting with `num`

**Review by jpivarski — APPROVED** [review]
Great, thanks!

**Pull request merged**
