### PR TITLE
refactor!: make `Content` initialisers take `nplike`, `parameters` as keyword

### PR DESCRIPTION
**Pull request by agoose77**
----
:books: The documentation for this PR will be available at <https://awkward-array.readthedocs.io/en/agoose77-refactor-content-keyword/> once Read the Docs has finished building :hammer:

### CODE REVIEW

**Review by jpivarski — CHANGES_REQUESTED** [review]
Yes, but also for Forms and Types, since there's a strong symmetry between these and Contents (especially Forms).

I'll get started on that, adding to this PR, if that's alright.

**Review by jpivarski — APPROVED** [review]

**Comment by agoose77** [comment]
Fab, thanks for making this change. I was tempted to do them in multiple PRs, but on second thought it's less churn to do it all now. I didn't give it too much thought as I was playing around with `semgrep` to actually generate this PR

You can see the config that I used to do these renames, run with
```bash
semgrep -a --config=./rename.yaml
```

<details>
<summary> 
<code>rename.yaml</code>
</summary>

```yaml
rules:
- id: single-arg
  patterns:
    - pattern: '$F($X, $Y, $Z, $Q, $W, $U)'
    - metavariable-regex:
        metavariable: $F
        regex: ^.*ListArray$
  languages: [python]
  severity: WARNING
  message: Semgrep found a match
  fix: $F($X, $Y, $Z, $Q, $W, parameters=$U)
  ```

</details>

It wasn't perfect; sometimes it mangled the source. But careful staging worked well.

**Comment by jpivarski** [comment]
We were thinking along the same lines: I wanted to make them separate commits, rather than separate PRs, so that they can be checked in stages. It's just a question of what granularity the `main` branch should have. (After this refactoring is done, it's unlikely someone will want to see them separately, and if they do, they can follow the merge commit to this PR and see the individual commits.)

**Comment by agoose77** [comment]
I ran a check over the forms with
```yaml
rules:
- id: single-arg
  patterns:
    - pattern: '$F(...)'
    - pattern-not: '$F(..., parameters=$X)'
    - metavariable-regex:
        metavariable: $F
        regex: ^.*Type$
  languages: [python]
  severity: WARNING
  message: Semgrep found a match
```
and visually ensured the correct results

**Pull request merged**
