### PR TITLE
fix: make sure 'at' is a cupy zero dim array

### LINKED ISSUE #3280: `pytest tests-cuda-kernels` is currently failing on my GPU
### Version of Awkward Array

HEAD

### Description and code to reproduce

But `pytest tests-cuda` works.

After the first failing test, they all fail: something is sticky.

```
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_jagged_expand_64.py s                    [  7%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_array_64.py .......                 [  7%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_array_advanced_64.py ...............[  8%]
...............                                                                                  [  8%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_at_64.py FF                         [  8%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_range_64.py s                       [  8%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_range_carrylength.py s              [  8%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_range_counts_64.py FFFFF            [  8%]
tests-cuda-kernels/test_cudaawkward_ListArray32_getitem_next_range_spreadadvanced_64.py s        [  8%]
```

@ianna says,

> the problem is because of the generated tests. It’s the generated data for `at` that now should be `cupy.array(0)` instead of `0`.

### PR DESCRIPTION
**Pull request by ianna**
fixes https://github.com/scikit-hep/awkward/issues/3280

### CODE REVIEW

**Comment by ianna** [comment]
@martindurant - I hope this PR fixes your issue with indexing.

**Comment by martindurant** [comment]
Wow, thanks for looking into it!

**Comment by ianna** [comment]
fixes https://github.com/scikit-hep/awkward/issues/3280

**Review by ianna — COMMENTED** [review]
@jpivarski - the tests pass integers. The Python wrapping of the kernels converts the 'at' parameter to a cupy array.

**Review by jpivarski — APPROVED** [review]
Yes, this passes all tests on my GPU and it's ready to be merged. Thank you!

**Pull request merged**
