### PR TITLE
refactor: removed placeholder (-1) intended for Identifier from Lookup.

### PR DESCRIPTION
**Pull request by jpivarski**
This is a follow-up on #1845, which removed Identifers (known as Identities in v1). The `Lookup` arrays used by Awkward's Numba and RDataFrame integration had a placeholder for pointers to (lowered) Identifiers, which this PR removes.

It's a potentially delicate operation, since a misplaced item in a `Lookup` array would lead to a segfault or worse. That's why this is a separate PR, so that it's a clear step in the global history. However, this PR and the 22 files of tests that depend on it:

- tests/test_0118-numba-cpointers.py
- tests/test_0124-strings-in-numba.py
- tests/test_0127b-tomask-operation-numba.py
- tests/test_0290-bug-fixes-for-hats.py
- tests/test_0395-fix-numba-indexedarray.py
- tests/test_0397-arrays-as-constants-in-numba.py
- tests/test_0549-numba-array-asarray.py
- tests/test_0559-fix-booleans-in-numba.py
- tests/test_0572-numba-array-ndim.py
- tests/test_0903-ArrayView-expects-contiguous-NumpyArrays.py
- tests/test_1240-v2-implementation-of-numba-1.py
- tests/test_1300-awkward-to-cpp-converter-with-cling.py
- tests/test_1300b-same-for-numba.py
- tests/test_1374-to-rdataframe.py
- tests/test_1473-from-rdataframe.py
- tests/test_1477-generator-entry-type-as-rvec.py
- tests/test_1508-awkward-from-rdataframe.py
- tests/test_1613-generator-tolayout-records.py
- tests/test_1620-layout-builders.py
- tests/test_1625-multiple-columns-from-rdataframe.py
- tests/test_1781-rdataframe-snapshot.py
- tests/test_1829-to-from-rdataframe-bool.py

Don't seem to have any issues. The tests run both in series and in parallel, all tests and just these. (Toggling things like that change the memory layout.) I know that the tests check exact expected values from compiled Numba and Cling code, so it's pretty secure.

I'll ask @ianna to review this one because it affects code she's working on (both Numba _and_ RDataFrame).

----
:books: The documentation for this PR will be available at <https://awkward-array.readthedocs.io/en/jpivarski-removed-identifier-placeholder-from-lookups/> once Read the Docs has finished building :hammer:

### CODE REVIEW

**Review by ianna — APPROVED** [review]
Great! All tests pass, including the examples from a tutorial. Awkward types in RDataFrame are transient, as such there is no backward incompatibility.

Unrelated to this PR: there is one compilation warning (I don't know why I missed it earlier):
```zsh
In file included from /Users/yana/Projects/PR1852/awkward/src/libawkward/builder/Complex128Builder.cpp:7:
In file included from /Users/yana/Projects/PR1852/awkward/include/awkward/builder/OptionBuilder.h:10:
/Users/yana/Projects/PR1852/awkward/src/awkward/cpp-headers/awkward/GrowableBuffer.h:138:59: warning: implicit conversion from 'long long' to 'double' may lose precision [-Wimplicit-int-float-conversion]
        to_ptr[offset++] = static_cast<TO_PRIMITIVE>(ptr_.get()[i]);
                           ~~~~~~~~~~~               ~~~~~^~~~~~~~
/Users/yana/Projects/PR1852/awkward/src/awkward/cpp-headers/awkward/GrowableBuffer.h:288:21: note: in instantiation of function template specialization 'awkward::Panel<long long>::copy_as<std::complex<double>>' requested here
      other.panel_->copy_as(rawptr, 0);
                    ^
/Users/yana/Projects/PR1852/awkward/src/libawkward/builder/Complex128Builder.cpp:24:42: note: in instantiation of function template specialization 'awkward::GrowableBuffer<long long>::copy_as<std::complex<double>>' requested here
      std::move(GrowableBuffer<int64_t>::copy_as<std::complex<double>>(old)));
                                         ^
```

**Comment by jpivarski** [comment]
Yes, I saw that locally on my Mac, but not in the CI. I couldn't figure out what to do with it because it's already being cast. (Switching the `static_cast` syntax for a C-style cast doesn't change anything.)

But having only one warning to ignore is a better situation to be in than a hundred warnings to ignore. The problem is being able to see new issues come up through the smokescreen of old warnings, so fewer is better, but the difference between zero and one is not a make-or-break difference.

**Comment by ianna** [comment]
> Yes, I saw that locally on my Mac, but not in the CI. I couldn't figure out what to do with it because it's already being cast. (Switching the `static_cast` syntax for a C-style cast doesn't change anything.)
> 
> But having only one warning to ignore is a better situation to be in than a hundred warnings to ignore. The problem is being able to see new issues come up through the smokescreen of old warnings, so fewer is better, but the difference between zero and one is not a make-or-break difference.

I think, a specialization fixes it. Please, check - thanks!

**Comment by ianna** [comment]
oh... sorry, did I break the build?

**Comment by jpivarski** [comment]
Is `copy_as` a special C++ function? The warning was in a cast that had no mention of "`copy_as`" anywhere, so if this does fix it, I'm mystified.

The failure in one of the tests appears to be a compilation error in the new code:

```
      [  3%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/awkward_ByteMaskedArray_getitem_nextcarry.cpp.o
      In file included from /home/runner/work/awkward/awkward/include/awkward/builder/OptionBuilder.h:10,
                       from /home/runner/work/awkward/awkward/src/libawkward/builder/BoolBuilder.cpp:7:
      /home/runner/work/awkward/awkward/src/awkward/cpp-headers/awkward/GrowableBuffer.h:146:15: error: explicit specialization in non-namespace scope ‘class awkward::Panel<PRIMITIVE>’
        146 |     template <>
            |               ^
      make[2]: *** [CMakeFiles/awkward-objects.dir/build.make:90: CMakeFiles/awkward-objects.dir/src/libawkward/builder/BoolBuilder.cpp.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/awkward-objects.dir/all] Error 2
      make[1]: *** Waiting for unfinished jobs....
```

It only seems to affect Linux/gcc, though.

**Comment by ianna** [comment]
Yes, this should be allowed if a compiler is a C++14 compliant :-(
```
/home/runner/work/awkward/awkward/src/awkward/cpp-headers/awkward/GrowableBuffer.h:146:15: error: explicit specialization in non-namespace scope ‘class awkward::Panel<PRIMITIVE>’
[592](https://github.com/scikit-hep/awkward/actions/runs/3385889893/jobs/5624580498#step:7:593)
    146 |     template <>
[593](https://github.com/scikit-hep/awkward/actions/runs/3385889893/jobs/5624580498#step:7:594)
        |               ^
[594](https://github.com/scikit-hep/awkward/actions/runs/3385889893/jobs/5624580498#step:7:595)
```

**Comment by ianna** [comment]
> Is `copy_as` a special C++ function? The warning was in a cast that had no mention of "`copy_as`" anywhere, so if this does fix it, I'm mystified.
> 
> The failure in one of the tests appears to be a compilation error in the new code:
> 
> ```
>       [  3%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/awkward_ByteMaskedArray_getitem_nextcarry.cpp.o
>       In file included from /home/runner/work/awkward/awkward/include/awkward/builder/OptionBuilder.h:10,
>                        from /home/runner/work/awkward/awkward/src/libawkward/builder/BoolBuilder.cpp:7:
>       /home/runner/work/awkward/awkward/src/awkward/cpp-headers/awkward/GrowableBuffer.h:146:15: error: explicit specialization in non-namespace scope ‘class awkward::Panel<PRIMITIVE>’
>         146 |     template <>
>             |               ^
>       make[2]: *** [CMakeFiles/awkward-objects.dir/build.make:90: CMakeFiles/awkward-objects.dir/src/libawkward/builder/BoolBuilder.cpp.o] Error 1
>       make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/awkward-objects.dir/all] Error 2
>       make[1]: *** Waiting for unfinished jobs....
> ```
> 
> It only seems to affect Linux/gcc, though.

The warning originated in `Complex128Builder` where a buffer of `integers` is converted to a buffer of `complex` numbers:
```
/Users/yana/Projects/PR1852/awkward/src/libawkward/builder/Complex128Builder.cpp:24:42: note: in instantiation of function template specialization 'awkward::GrowableBuffer<long long>::copy_as<std::complex<double>>' requested here
      std::move(GrowableBuffer<int64_t>::copy_as<std::complex<double>>(old)));
                                         ^
```

**Comment by jpivarski** [comment]
I think the build is not C++14 compliant:

https://github.com/scikit-hep/awkward/blob/87049ac174e72584f09b4f0062a34c983f35a439/CMakeLists.txt#L50

What used to be in CMakeLists.txt was C++11 in general, C++14 for Windows because of the compilers available, but this seems to be saying it should be C++11 for everybody. The RDataFrame code uses C++17, but that's generated at runtime and uses Cling, rather than the compiler that builds the static libraries. Does any part of GrowableBuffer or LayoutBuilder use C++17?

I don't have strong opinions on what standard we _should_ be using. It used to be C++11 so that we could use old Python Docker images (`manylinux`), but that requirement went away with Python 2. If there's reason for the whole C++ codebase to be C++17, let's do it. But it doesn't look like that's what the CMakeLists.txt is saying.

**Comment by ianna** [comment]
I've reverted the commit. I do not see the compilation warning in a master branch checked out locally. Please, go ahead and merge this PR. I'll double check again. Thanks.

**Comment by ianna** [comment]
The master does not give any compilation warnings. However, if I enable my ROOT environment I get it. I'll try to check if this can be fixed - in another PR.

**Pull request merged**
