### PR TITLE
test: growablebuffer move_to

### PR DESCRIPTION
**Pull request by ianna**
test if releasing memory earlier helps with https://github.com/scikit-hep/awkward/issues/2440

### CODE REVIEW

**Comment by ianna** [comment]
@lgray - this PR implements a more aggressive memory release policy in building Awkward Arrays. Though, I do not see much difference with your test on my Mac. Could you, please, test it within a realistic analysis and see if it makes any difference? Thanks!

**Comment by lgray** [comment]
Hi @ianna we're largely finding, I think, that macos is kind of weird when it comes to memory. The answers are very different w.r.t. linux. 

I'll try this out but if you have a linux machine to try it on - I'd check there!

**Comment by jpivarski** [comment]
This PR is addressing an issue that has already been closed for other reasons, and it's months old. I'm going to guess that it is not needed anymore and will close it. If I'm wrong, we can reopen it.

**Review by ianna — COMMENTED** [review]
@jpivarski - this PR tests an existing code. I don't think I need to keep the branch.

**Pull request closed without merging**
