### PR TITLE
Keep writing those Python docs.

### PR DESCRIPTION
**Pull request by jpivarski**
* [x] Handmade `ak.layout.Content` subclasses.
   * [x] Handmade `ak.layout.Record`.

### CODE REVIEW

**Comment by Ellipse0934** [comment]
@jpivarski Hi, I didn't mean to disturb. Can you check your email ? I will delete this message soon.

**Comment by jpivarski** [comment]
> @jpivarski Hi, I didn't mean to disturb. Can you check your email ? I will delete this message soon.

I'm checking my email. (That's how I got this message, after all.)

**Comment by Ellipse0934** [comment]
Did you receive any mails lately ? I sent one 17 hours ago related to the GSoC project.

**Comment by jpivarski** [comment]
> Did you receive any mails lately ? I sent one 17 hours ago related to the GSoC project.

I did, but it's a long one and will take me some time to get through all the materials and questions. I was looking for a long enough block to dedicate to it.

**Comment by Ellipse0934** [comment]
Fair enough. Hopefully, you can get through them by the end of the day. I shall send a draft proposal within the next 2 hours. If you could review that it would be great. 
Thank You

**Pull request merged**
