### PR TITLE
Generate Python code for CPU kernels

### PR DESCRIPTION
**Pull request by reikdas**
@jpivarski 
@trickarcher although this may not be directly relevant to your infrastructure code, you might be interested in taking a look :)

### CODE REVIEW

**Comment by jpivarski** [comment]
Great start!

**Review by jpivarski — DISMISSED** [review]
It looks good from this altitude! (Maybe just put the LICENSE comment line at the top of dev/genpython.py.

What does the generated documentation look like? You could attach some screenshots to the GitHub comments.

It looks like the dev/genpython.py does all of the parsing and formatting for documentation, but for making the unit tests, you'll need to factorize it somewhat. That can come in the next PR, though.

**Comment by reikdas** [comment]
> Maybe just put the LICENSE comment line at the top of dev/genpython.py.

Done.

> What does the generated documentation look like? You could attach some screenshots to the GitHub comments.

image

**Comment by jpivarski** [comment]
Okay, I like the choice of putting it last in the left-bar, since it is the most internal of internal interfaces. It should probably be called "kernels," rather than "cpukernels," and get some text at the beginning explaining what this is all about, but that can come later. There's no bulleted-list-as-table-of-contents, but I had forgotten that the left-bar expands when you open one of these, so everything that we need is there.

When a function has several type variants, like `awkward_ListArray_min_range`, how do you find out that the corresponding real names are

   * `awkward_ListArray32_min_range`
   * `awkward_ListArrayU32_min_range`
   * `awkward_ListArray64_min_range`

Are they in a bulleted list below the screenshot you showed? They could be given as three blue signatures below the heading. Then you wouldn't need the `for C in int` which is wrong (can't be evaluated; `int` isn't iterable; you probably intended it for cases like `for C in (bool, int, float)` but it came out wrong in this case).

If it makes things any easier, you could just pretend that `int32_t`, `uint32_t`, `int64_t` are Python types, as though someone did this:

```python
>>> int32_t = int
>>> uint32_t = int
>>> int64_t = int
```

When we evaluate them for tests, we can put that in the preamble.

The requirements are (a) we have to be able to look up the real names of the function, such as `awkward_ListArray32_min_range`, because that's what ctypes sees, (b) the Python code needs to be executable, because we'll want to use exactly the same code in the tests, to demonstrate that these really are the definitions, and (c) type-variants of the same function (defined in terms of the same templated code, internally) need to be grouped somehow.

It would be enough to make it look like this:

```
awkward_ListArray_min_range
===========================

.. py:function:: awkward_ListArray32_min_range(tomin: List[int64_t], fromstarts: List[int32_t], fromstops: List[int32_t], lenstarts: int64_t, startsoffset: int64_t, stopsoffset: int64_t)

.. py:function:: awkward_ListArrayU32_min_range(tomin: List[int64_t], fromstarts: List[uint32_t], fromstops: List[uint32_t], lenstarts: int64_t, startsoffset: int64_t, stopsoffset: int64_t)

.. py:function:: awkward_ListArray64_min_range(tomin: List[int64_t], fromstarts: List[int64_t], fromstops: List[int64_t], lenstarts: int64_t, startsoffset: int64_t, stopsoffset: int64_t)

.. code-block:: python

    def awkward_ListArray_min_range(
        tomin,
        fromstarts,
        fromstops,
        lenstarts,
        startsoffset,
        stopsoffset
    ):
        shorter = fromstops[stopsoffset + 0] - fromstarts[startsoffset + 0]
        for i in range(lenstarts):
            range = fromstops[stopsoffset + i] - fromstarts[startsoffset + i]
            shorter = (shorter < range) if shorter else range
        tomin[0] = shorter

    awkward_ListArray32_min_range = awkward_ListArray_min_range
    awkward_ListArrayU32_min_range = awkward_ListArray_min_range
    awkward_ListArray64_min_range = awkward_ListArray_min_range
```

(Or some other simple way to indicate that the three type variants correspond to the one implementation, without a lot of verbiage.)

A few things I found in typing this out: (1) there's a terrible bug in the original function: `startsoffset` was used in `fromstops` and `stopsoffset` was used in `fromstarts`. The bug never caused an error because it's likely that the offsets have always been zero, but it's a ticking time bomb. Can you please fix this (in another PR, if you want to keep it separate from this work) and search for cases where offsets are used with the wrong arrays? They are _always_ linked by name; you'll always be able to tell. If you fix that and all tests continue to pass, then we're nevertheless in a much better state because these bugs will reveal themselves as segfaults, and would be hard to debug.

The second thing is (2) the `tomin` assignment must be `tomin[0] = shorter`. Otherwise, Python can't export the value of `tomin` from the function. In the signatures, you're saying it's a `List`, let's take that seriously and use it that way because it's the only way to translate the assignment-through-pointer of C into Python. There aren't any `&tomin` instances in the codebase—explicit pointers are used throughout, so that should make it easier.

(3) This while loop wasn't translated into a for loop. I don't see any reason why it can't be—it has simple structure.

(4) Python builtin function names like `range` should be given the same treatment as keywords like `from`: we should avoid them in these code blocks because they're needed for things like making for loops. You don't have to look up a whole list of builtins to avoid, fixing `range` should be enough for now.

Sorry I found so many things to fix! I wanted to merge this and move on to testing, but some of these things will bite us in the tests. (It's probably a good hint that the tests should include non-zero offsets, to find any other bugs like the one above.)

**Comment by reikdas** [comment]
> It should probably be called "kernels," rather than "cpukernels,"

Done.

I made the functions having various template type variants look like this - 
image

image
What do you think?

> The second thing is (2) the tomin assignment must be tomin[0] = shorter

I made all `*x = y` assignments into `x[0] = y`. 

> (3) This while loop wasn't translated into a for loop. 

Done.

> (4) Python builtin function names like range should be given the same treatment as keywords like from: we should avoid them in these code blocks because they're needed for things like making for loops. 

Done.

**Comment by jpivarski** [comment]
I know I said earlier that integer types should all be `int` in Python, but we have to distinguish the integer specializations, so revert to `int32_t`, `uint32_t`, `int64_t`. It's a matter of removing the code that maps all of them to `int`. Same for `float` vs `double`. We can pretend that these symbols have been defined in Python, as that's easy to do in the testing code.

The signatures are all on the specialized functions (in blue), so they don't need to be generalized in the implementation, which means that you don't need a `C` or a `C = int`. See my code example.

After that, the documentation is perfect.

But then there's still the issue of the wrong offsets being used, discovered by looking at this documentation, but independent of it. That can be another PR, but a sweep through all kernels, looking for this type of mistake, needs to be done.

**Comment by reikdas** [comment]
image
@jpivarski What do you think?

There is specialized code in genpython.py to deal with functions having dynamic memory arrays like https://github.com/scikit-hep/awkward-1.0/blob/master/src/cpu-kernels/operations.cpp#L3307. I'll remove that code(to make the cpu-kernels check stricter) when I refactor the code to remove the dynamic size allocation.

**Comment by jpivarski** [comment]
This looks great! I'd merge it now if you're ready. Are you?

**Comment by reikdas** [comment]
> This looks great! I'd merge it now if you're ready. Are you?

Yes :)

**Pull request merged**
