### PR TITLE
feat: add miscellaneous CUDA kernels

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Added following CUDA kernels:
- awkward_IndexedArray_flatten_none2empty
- awkward_ListArray_combinations_length
- awkward_ListOffsetArray_local_preparenext
- awkward_sorting_ranges
- awkward_ListArray_rpad_axis1 (variable-length inner loop)
- awkward_ListOffsetArray_rpad_axis1
- awkward_NumpyArray_pad_zero_to_length

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@jpivarski Packaging tests for ubuntu seem to be failing for all PRs

**Comment by jpivarski** [comment]
It's not finding `numpy.AxisError`, and it looks like it's installing numpy-1.26.4, not NumPy 2.0 or anything. That's very strange. Maybe it's installing a different NumPy at a later stage in the workflow? (I didn't follow it through to the end.)

**Comment by ManasviGoyal** [comment]
> It's not finding `numpy.AxisError`, and it looks like it's installing numpy-1.26.4, not NumPy 2.0 or anything. That's very strange. Maybe it's installing a different NumPy at a later stage in the workflow? (I didn't follow it through to the end.)

I do see NumPy 2.0 before the error
```
Successfully installed awkward-cpp-30 numpy-2.0.0b1
```

**Comment by jpivarski** [comment]
Then #2936 has arrived, @tcawlfield!

**Review by jpivarski — APPROVED** [review]
Looks great! I thought I had reviewed and merged this earlier, but apparently hadn't. I had no comments or changes then, so I'll merge it now.

**Pull request merged**
