### PR TITLE
Add a CITATION.cff file to specify a set of authors.

### PR DESCRIPTION
**Pull request by jpivarski**
@ianna, @ioanaif, @henryiii, @agoose77, @swishdiff, @reikdas, @SantamRC, @nsmith-: we're going to be referencing Awkward Array in a paper @aryan26roy is writing, and Zenodo's auto-generated list of authors is too large. Also, I've been meaning to do this ever since scikit-hep/scikit-hep/pull/159 (also for Uproot, though that will be another day).

This list includes

   1. All the Princeton people who are explicitly working on this project: me, Yana, Ioana, Henry, and soon Angus.
   2. All the students whose projects explicitly contributed to it: Anish, Reik, and Santam.
   3. Nick, who made significant contributions. (Angus would be in this category, too, if not the first.)

Am I missing anyone that I should be considering? I have to make a cutoff somewhere, which is hard to do (and it's why we have the all-contributors box).

Also Angus, Santam, and Nick, if you have an ORCID, I can add it.

Thanks!

### CODE REVIEW

**Comment by SantamRC** [comment]
@jpivarski thanks for the mention. This is my ORCID Number - 0000-0003-0153-9748

**Comment by agoose77** [comment]
My ORCID is https://orcid.org/0000-0003-0788-3814 :)

**Comment by henryiii** [comment]
You could use a [GitHub citation file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)? Zenodo picks those up too though I think there were some limitations.

**Comment by ianna** [comment]
@jpivarski - Thanks!. Mine is https://orcid.org/0000-0002-6955-1033

**Comment by jpivarski** [comment]
Thanks for the ORCIDs! 

> You could use a [GitHub citation file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)? Zenodo picks those up too though I think there were some limitations.

Since I don't have a reason to prefer .zenodo.json and CITATION.cff sounds more vendor-independent, I switched to that. The CITATION.cff doesn't seem to have a section for description or license type, but that information is already available in the repo in standardized ways.

It does, however, have the option to add email addresses for everyone. _I only added an email address if I could find it publicly online._ If you'd rather not have your email listed here, or would rather a different address from the one I found, I can change it.

Awkward Array didn't have a clear release date, since I put a package on PyPI before it even had any code. For future reference, the date of "2018-10-12" comes from the [0.2.0 release](https://github.com/scikit-hep/awkward-0.x/releases/tag/0.2.0), which has release notes, "Finished a basic implementation of all planned awkward array classes," and the [earliest issues not written by me](https://github.com/scikit-hep/awkward-0.x/issues?q=is%3Aissue+created%3A%3C2018-11-01+-author%3Ajpivarski) come from around this date (October 15, 2018). This CITATION.cff looks like YAML; presumably I could add this information directly in the file as a comment, but I'd rather not risk it.

**Comment by henryiii** [comment]
A benefit of the citation file is it shows up in the GitHub rendering of the main page, in the side bar.

**Comment by jpivarski** [comment]
I'm enabling auto-merge, so in a half-hour or so this will be merged. If anyone has any future changes they'd like to make, just edit it and open a PR. Thanks!

**Pull request merged**
