### PR TITLE
chore: update CITATION.cff

### LINKED ISSUE #1713: Add Manasvi (and any others?) to CITATION.cff / Zenodo
@jpivarski are you happy with this?

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #1713

### CODE REVIEW

**Comment by jpivarski** [comment]
To answer your question from issue #1713, yes, Manasvi definitely qualifies as an author and I think she should be added to the list.

Is this good with you, @ManasviGoyal? Would you prefer a different email and do you have an ORCID? If you don't have an ORCID, it's easy to set one up: https://orcid.org/ This is a unique identifier that links all of your academic publications.

**Comment by ManasviGoyal** [comment]
> To answer your question from issue #1713, yes, Manasvi definitely qualifies as an author and I think she should be added to the list.
> 
> Is this good with you, @ManasviGoyal? Would you prefer a different email and do you have an ORCID? If you don't have an ORCID, it's easy to set one up: https://orcid.org/ This is a unique identifier that links all of your academic publications.

Yes, @jpivarski this email works. I have set up an ORCID. here is the link - https://orcid.org/0000-0001-6321-7491. @agoose77 please add this too. Thanks.

**Comment by jpivarski** [comment]
Great! Then I'll merge the new author list.

**Comment by ManasviGoyal** [comment]
@agoose77 I was checking the doi link and noticed that the authors and the commits on zenodo are not up to date with the changes made to the `CITATION.cff`. Just wanted to bring it to your notice if it's something unusual. Thanks.

**Comment by agoose77** [comment]
I believe the Zenodo information will update when we next make a release, right @jpivarski?

**Comment by jpivarski** [comment]
Yes, that's correct. I discovered it experimentally yesterday with Uproot: adding a CITATION.cff when there hasn't been one before had no effect on Zenodo until I made a release. Uproot releases take a few minutes to make, but Awkward takes 4 hours, though maybe that will be a bit less (1 hour?) with v1 dropped. We'll be making such a release soon, and I can make sure to tell you when that happens.

**Pull request merged**
