### PR TITLE
Do not allow dynamic sized arrays in cpu-kernels

### PR DESCRIPTION
**Pull request by reikdas**

### CODE REVIEW

**Comment by jpivarski** [comment]
Do you need the results of the currently ongoing test, or can I cancel it to run #270? (Numba just released 0.50 yesterday, and this will become the minimum required version because it fixes a long-standing entry-point issue.) I want to see if the #270 test is successful so that I can merge it and make a new version that depends on the new Numba.

**Comment by reikdas** [comment]
Go ahead and cancel it :) 
But we should probably restart the tests later to make sure nothing breaks (I am done with this PR).

**Comment by jpivarski** [comment]
In that case, I've waited long enough by round-robining through my other emails that we should let this one finish, since the results of the test are going to be used for something (evaluating this PR that you're done with).

**Review by jpivarski — APPROVED** [review]
I know these two arrays were originally named `toindex` and `fromindex`, but when names like that are used on argument lists, the very loose convention that's been developing would expect them to be an array to write (`toindex`) and an array to read (`fromindex`, which would require an offset for reading). Actually, both of them are in a very unusual position of being scratch-work: they're written to as a step in the algorithm, but neither the input nor the output values are meaningful.

Maybe their names should be `tmp_toindex` and `tmp_fromindex`? On the other hand, that convention isn't well defined and you can probably find other cases where it has been broken because I didn't sit down and decide on formal names before I began. We could leave such a naming-convention sweep for the future. Now that we have a suite of a hundred functions, it would be possible to survey all the roles the arguments play and organize both the naming and the order of arguments with a formal rubric. That sweep should be done all at once, and in the future (not now). It should also be done with an IDE that understands enough of the C code to automate the renaming and reordering: we wouldn't want to introduce bugs in such a process.

So if this passes tests, I'll merge it and it will go in the new version I'm about to deploy.

**Pull request merged**
