### PR TITLE
Make ak.Array a Pandas DType extension.

### PR DESCRIPTION
**Pull request by jpivarski**
I.e. implement issue #63.

### CODE REVIEW

**Comment by jpivarski** [comment]
FYI @mhedges, this is where I'm incorporating your work. Unlike last time, I'm going to make all `ak.Arrays` subclasses of the Pandas extension type if Pandas is importable. There's a startup cost associated with this, but it's not too bad:

| | slow computer | medium computer | fast computer |
|:-|:-:|:-:|:-:|
| only Pandas | 1.5 sec | 0.35 sec | 0.25 sec |
| only Numba | 1.0 sec | 0.35 sec | 0.20 sec |
| both Pandas and Numba | 2.0 sec | 0.60 sec | 0.35 sec |

where "slow computer" is a Chromebook. Having to wait 2 seconds for `awkward1` to import on a computer like that shouldn't be too much of a surprise.

**Comment by jpivarski** [comment]
**Update:** as it turns out, we don't need to `import pandas` just to make `ak.Array` inherit from `pandas.api.extensions.ExtensionArray`. You can change base classes at runtime! ([In Python 2.7 and 3.2+](https://stackoverflow.com/a/9639512/1623645).)

https://github.com/scikit-hep/awkward-1.0/blob/cc7bf633ba0f4dd3d96a2990bcf16b15192c4dfc/awkward1/_pandas.py#L46-L55

So we can avoid the 2 second startup time on slow computers. The Numba startup time can be avoided by registering it as a [Numba entry point](https://numba.pydata.org/numba-doc/dev/extending/entrypoints.html), which I haven't done yet, but it's available as long as I require `numba>=0.46.0`.

**Comment by jpivarski** [comment]
@nsmith-: The internal `called_by_module` function

https://github.com/scikit-hep/awkward-1.0/blob/db6938d82a41be90266945909244181c65b49a7b/awkward1/highlevel.py#L12-L19

will ensure that Matplotlib is not allowed to iterate over an array, while still letting everybody else do it. It's a blacklist against bad actors.

https://github.com/scikit-hep/awkward-1.0/blob/db6938d82a41be90266945909244181c65b49a7b/awkward1/highlevel.py#L72-L78

I already need it for Pandas: Pandas uses `__array__` on a subset of array elements to print them to the screen. For this case, I don't mind returning NumPy object arrays, because they're necessarily small (or the printing would be a bottleneck, anyway). But in general, `ak.Array` should only be coerced to a NumPy array if it can do so as a non-object array, preserving structure.

https://github.com/scikit-hep/awkward-1.0/blob/db6938d82a41be90266945909244181c65b49a7b/awkward1/highlevel.py#L96-L106

This _does_ feel like a hack, I know, but it's only applied to the high level object (`ak.Array`). It exists because these third-party libraries should have introduced a protocol that doesn't name-clash with a preexisting one, or they assumed that their `__iter__`/`__array__` needs would be the same as anybody else's.

The `inspect` module might have a performance penalty, but these are methods that shouldn't be used in tight loops, anyway.

**Comment by jpivarski** [comment]
@nsmith- I ended up inhibiting Matplotlib by correctly implementing `np.size` and `np.atleast_1d` with reasonable definitions for Awkward arrays.

   * `np.size` only gives a value if the axis in question is a RegularArray. `plt.hist` queries them all (`axis=None`), which will raise an error suggesting `ak.flatten` or `ak.tonumpy` if it contains any jagged arrays.
   * `np.atleast_1d` has to be able to cast all its arguments as NumPy arrays (of at least one dimension). If any Awkward arrays fail `ak.tonumpy`, this will fail.

https://github.com/scikit-hep/awkward-1.0/blob/a9b166ef490be2cd2e98ace5092d57d13563235a/tests/test_PR089_numpy_functions.py#L169-L181

So... not a hack! (This probably requires `numpy>=1.17` though. Users of Matplotlib with older NumPy versions might get the old failure, but a situation in which the old failure gradually recedes into the past is acceptable, I think.)

However, `ak.Array.__array__` still checks to see if it's being called by Pandas and creates a NumPy object array only for Pandas. (All other cases attempt `ak.tonumpy`.)

**Comment by jpivarski** [comment]
@mhedges This is a complete implementation of Awkward-in-Pandas, derived heavily from your work in Awkward 0. It also avoids the 2 second startup time by having `PandasMixin` inherit from `PandasNotImportedYet` until the first time its `dtype` is queried, then it retroactively inherits from `pandas.api.extensions.ExtensionArray` (for all existing arrays, too).

The only loophole I see is that someone might do this:

```python
pd.DataFrame({"column": [... lists of lists ...]}, dtype="awkward1")
```

and it will say that `"awkward1"` has not been registered as a dtype _if_ the import-on-demand has not been triggered yet. I'll put that off to see if it becomes an issue in practice.

The full Pandas test suite works:

https://github.com/scikit-hep/awkward-1.0/blob/a9b166ef490be2cd2e98ace5092d57d13563235a/tests/test_PR090_as_pandas_extension.py#L195-L196

**Comment by mhedges** [comment]
This is awesome! So cool to see it come together.  That's pretty slick move to wait to import from pandas until runtime

**Pull request merged**
