### PR TITLE
Bugfix for NumpyArray 32-bit vs 64-bit errors

### PR DESCRIPTION
**Pull request by ianna**
* fix NumpyArray 32-bit vs 64-bit errors

### CODE REVIEW

**Comment by ianna** [comment]
@jpivarski - I do not see any warnings or errors in the build.

**Comment by jpivarski** [comment]
I'll have to check it when I get in, because there _were_ a few in operations.cpp.

Also, you may want to change the name of this pill request.

**Comment by jpivarski** [comment]
Looking at the [last Python 3.7, 32-bit test](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=1054&view=logs&jobId=14431b54-d949-5b45-5c5a-199a6962c9d9&j=14431b54-d949-5b45-5c5a-199a6962c9d9&t=0a366409-8179-5e51-c0fe-d3dc52b6ba4f), I see these warnings from Visual Studio:

```
2020-01-30T11:34:09.0342649Z Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
2020-01-30T11:34:09.0343483Z Copyright (C) Microsoft Corporation. All rights reserved.
2020-01-30T11:34:09.0343737Z 
2020-01-30T11:34:09.4825119Z   Checking Build System
2020-01-30T11:34:09.6213315Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:34:09.8561716Z   Content.cpp
2020-01-30T11:34:10.5684550Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:34:11.6208142Z   getitem.cpp
2020-01-30T11:34:11.6624677Z   identities.cpp
2020-01-30T11:34:11.7332313Z   Identities.cpp
2020-01-30T11:34:11.8898799Z   operations.cpp
2020-01-30T11:34:12.2951423Z D:\a\1\s\src\cpu-kernels\operations.cpp(127): warning C4244: '=': conversion from 'T' to 'C', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-cpu-kernels-objects.vcxproj]
2020-01-30T11:34:12.2967992Z           with
2020-01-30T11:34:12.2968954Z           [
2020-01-30T11:34:12.2969553Z               T=int64_t
2020-01-30T11:34:12.2970106Z           ]
2020-01-30T11:34:12.2970657Z           and
2020-01-30T11:34:12.2971211Z           [
2020-01-30T11:34:12.2971747Z               C=int32_t
2020-01-30T11:34:12.2972302Z           ]
2020-01-30T11:34:12.3003505Z   D:\a\1\s\src\cpu-kernels\operations.cpp(133): note: see reference to function template instantiation 'Error awkward_listarray_flatten_scale<int32_t,int64_t>(C *,C *,const T *,const C *,const C *,int64_t,int64_t,int64_t)' being compiled
2020-01-30T11:34:12.3004586Z           with
2020-01-30T11:34:12.3004760Z           [
2020-01-30T11:34:12.3006332Z               C=int32_t,
2020-01-30T11:34:12.3015414Z               T=int64_t
2020-01-30T11:34:12.3019796Z           ]
2020-01-30T11:34:12.3020153Z D:\a\1\s\src\cpu-kernels\operations.cpp(128): warning C4244: '=': conversion from 'T' to 'C', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-cpu-kernels-objects.vcxproj]
2020-01-30T11:34:12.3021382Z           with
2020-01-30T11:34:12.3021765Z           [
2020-01-30T11:34:12.3028695Z               T=int64_t
2020-01-30T11:34:12.3032720Z           ]
2020-01-30T11:34:12.3032988Z           and
2020-01-30T11:34:12.3033859Z           [
2020-01-30T11:34:12.3034242Z               C=int32_t
2020-01-30T11:34:12.3042298Z           ]
2020-01-30T11:34:12.3051761Z D:\a\1\s\src\cpu-kernels\operations.cpp(127): warning C4244: '=': conversion from 'T' to 'C', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-cpu-kernels-objects.vcxproj]
2020-01-30T11:34:12.3052263Z           with
2020-01-30T11:34:12.3052432Z           [
2020-01-30T11:34:12.3052563Z               T=int64_t
2020-01-30T11:34:12.3052713Z           ]
2020-01-30T11:34:12.3056491Z           and
2020-01-30T11:34:12.3061461Z           [
2020-01-30T11:34:12.3061967Z               C=uint32_t
2020-01-30T11:34:12.3066680Z           ]
2020-01-30T11:34:12.3071257Z   D:\a\1\s\src\cpu-kernels\operations.cpp(136): note: see reference to function template instantiation 'Error awkward_listarray_flatten_scale<uint32_t,int64_t>(C *,C *,const T *,const C *,const C *,int64_t,int64_t,int64_t)' being compiled
2020-01-30T11:34:12.3074616Z           with
2020-01-30T11:34:12.3078488Z           [
2020-01-30T11:34:12.3078758Z               C=uint32_t,
2020-01-30T11:34:12.3079626Z               T=int64_t
2020-01-30T11:34:12.3080023Z           ]
2020-01-30T11:34:12.3087167Z D:\a\1\s\src\cpu-kernels\operations.cpp(128): warning C4244: '=': conversion from 'T' to 'C', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-cpu-kernels-objects.vcxproj]
2020-01-30T11:34:12.3091967Z           with
2020-01-30T11:34:12.3092249Z           [
2020-01-30T11:34:12.3092396Z               T=int64_t
2020-01-30T11:34:12.3092553Z           ]
2020-01-30T11:34:12.3097076Z           and
2020-01-30T11:34:12.3101492Z           [
2020-01-30T11:34:12.3104128Z               C=uint32_t
2020-01-30T11:34:12.3104337Z           ]
2020-01-30T11:34:12.3472381Z   util.cpp
2020-01-30T11:34:12.7634225Z   Generating Code...
2020-01-30T11:34:12.9753627Z   Index.cpp
2020-01-30T11:34:14.0167956Z   awkward-cpu-kernels-objects.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\awkward-cpu-kernels-objects.dir\Release\awkward-cpu-kernels-objects.lib
2020-01-30T11:34:14.1293420Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:34:14.2033314Z   awkward-cpu-kernels-static.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\awkward-cpu-kernels-static.lib
2020-01-30T11:34:14.2307013Z   Iterator.cpp
2020-01-30T11:34:14.7652179Z   Slice.cpp
2020-01-30T11:34:15.4430062Z   EmptyArray.cpp
2020-01-30T11:34:16.1074344Z   IndexedArray.cpp
2020-01-30T11:34:16.9356028Z   ListArray.cpp
2020-01-30T11:34:17.7094159Z   ListOffsetArray.cpp
2020-01-30T11:34:18.4777061Z   None.cpp
2020-01-30T11:34:19.0961373Z   NumpyArray.cpp
2020-01-30T11:34:19.5621681Z D:\a\1\s\src\libawkward\array\NumpyArray.cpp(693): warning C4244: 'initializing': conversion from 'int64_t' to 'ssize_t', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-objects.vcxproj]
2020-01-30T11:34:19.5624319Z D:\a\1\s\src\libawkward\array\NumpyArray.cpp(710): warning C4244: 'initializing': conversion from 'int64_t' to 'ssize_t', possible loss of data [D:\a\1\s\build\temp.win32-3.7\Release\awkward-objects.vcxproj]
2020-01-30T11:34:20.0293191Z   Record.cpp
2020-01-30T11:34:20.7136389Z   RecordArray.cpp
2020-01-30T11:34:21.4486147Z   RegularArray.cpp
2020-01-30T11:34:22.2111553Z   UnionArray.cpp
2020-01-30T11:34:22.9764391Z   BoolFillable.cpp
2020-01-30T11:34:23.5506396Z   Fillable.cpp
2020-01-30T11:34:24.0527480Z   FillableArray.cpp
2020-01-30T11:34:24.5828354Z   FillableOptions.cpp
2020-01-30T11:34:24.9770832Z   Float64Fillable.cpp
2020-01-30T11:34:25.5495020Z   Generating Code...
2020-01-30T11:34:38.5708317Z   Compiling...
2020-01-30T11:34:38.5712446Z   GrowableBuffer.cpp
2020-01-30T11:34:39.1186775Z   Int64Fillable.cpp
2020-01-30T11:34:39.6864029Z   ListFillable.cpp
2020-01-30T11:34:40.2349211Z   OptionFillable.cpp
2020-01-30T11:34:40.7904155Z   RecordFillable.cpp
2020-01-30T11:34:41.4669696Z   StringFillable.cpp
2020-01-30T11:34:42.0887312Z   TupleFillable.cpp
2020-01-30T11:34:42.6972208Z   UnionFillable.cpp
2020-01-30T11:34:43.2968242Z   UnknownFillable.cpp
2020-01-30T11:34:43.8621706Z   json.cpp
2020-01-30T11:34:44.4764712Z   root.cpp
2020-01-30T11:34:45.0472018Z   ArrayType.cpp
2020-01-30T11:34:45.5622860Z   ListType.cpp
2020-01-30T11:34:46.1117652Z   OptionType.cpp
2020-01-30T11:34:46.6586402Z   PrimitiveType.cpp
2020-01-30T11:34:47.2361639Z   RecordType.cpp
2020-01-30T11:34:47.8650691Z   RegularType.cpp
2020-01-30T11:34:48.4088655Z   Type.cpp
2020-01-30T11:34:49.0768685Z   UnionType.cpp
2020-01-30T11:34:49.6631375Z   UnknownType.cpp
2020-01-30T11:34:50.2100864Z   Generating Code...
2020-01-30T11:34:57.4223131Z   Compiling...
2020-01-30T11:34:57.4224467Z   util.cpp
2020-01-30T11:34:58.1228147Z   Generating Code...
2020-01-30T11:34:59.4253097Z   awkward-objects.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\awkward-objects.dir\Release\awkward-objects.lib
2020-01-30T11:34:59.4650800Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:34:59.6294893Z   awkward-static.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\awkward-static.lib
2020-01-30T11:34:59.6687732Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:34:59.7483091Z   pyawkward.cpp
2020-01-30T11:35:28.7586843Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/layout.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/layout.exp
2020-01-30T11:35:28.9039575Z   Generating code
2020-01-30T11:36:03.5068033Z   Finished generating code
2020-01-30T11:36:04.1747497Z   layout.vcxproj -> D:\a\1\s\build\lib.win32-3.7\layout.cp37-win32.pyd
2020-01-30T11:36:04.2788832Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:36:05.6657674Z   test_PR019_use_json_library.cpp
2020-01-30T11:36:05.8704110Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:36:05.9169780Z   test_PR016_finish_getitem_for_rawarray.cpp
2020-01-30T11:36:06.2660396Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/PR019.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/PR019.exp
2020-01-30T11:36:06.2692547Z   PR019.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\PR019.exe
2020-01-30T11:36:06.3228195Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:36:06.3970117Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:36:06.4191992Z   Auto build dll exports
2020-01-30T11:36:06.9832904Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/awkward.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/awkward.exp
2020-01-30T11:36:07.0021242Z   awkward.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\awkward.dll
2020-01-30T11:36:07.0744900Z   test_PR030_recordarray_in_numba.cpp
2020-01-30T11:36:07.0770338Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/PR016.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/PR016.exp
2020-01-30T11:36:07.0773874Z   PR016.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\PR016.exe
2020-01-30T11:36:07.1049625Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
2020-01-30T11:36:07.1408036Z   Auto build dll exports
2020-01-30T11:36:07.2541013Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/awkward-cpu-kernels.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/awkward-cpu-kernels.exp
2020-01-30T11:36:07.4392439Z      Creating library D:/a/1/s/build/temp.win32-3.7/Release/Release/PR030.lib and object D:/a/1/s/build/temp.win32-3.7/Release/Release/PR030.exp
2020-01-30T11:36:07.4397722Z   PR030.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\PR030.exe
2020-01-30T11:36:07.4462533Z   awkward-cpu-kernels.vcxproj -> D:\a\1\s\build\temp.win32-3.7\Release\Release\awkward-cpu-kernels.dll
2020-01-30T11:36:07.5159743Z   Building Custom Rule D:/a/1/s/CMakeLists.txt
```

There's something remaining in NumpyArray.cpp lines 693 and/or 710, as well as the operations.cpp errors that I'll be testing now.

**Comment by jpivarski** [comment]
Actually, the NumpyArray.cpp ones were easy, so I fixed those, too.

**Comment by jpivarski** [comment]
And everything just broke for Python 3.6 and above because Pandas 1.0 has just been released. Apparently, what I developed for Pandas 0.24 has incompatibilities with 1.0. I'll add those fixes to this PR.

**Comment by ianna** [comment]
@jpivarski - here is a first step towards adding the compiler flags: https://github.com/scikit-hep/awkward-1.0/commit/db85e88c15295d81a067d69ba7188251630225c6
The list of flags is a guess. I can only test clang on MacOS.

**Comment by jpivarski** [comment]
@ianna I want to merge this as soon as it passes tests, so that I can merge it into my active branch. The commit you're referring to, db85e88, is that on this branch or another? If you want it in this PR, please add it quickly.

**Review by jpivarski — APPROVED** [review]

**Pull request merged**
