### PR TITLE
feat: add `empty_if_typetracer` & expose more of typetracer to L2

### PR DESCRIPTION
**Pull request by agoose77**
This PR:
- adds `ak.typetracer.empty_if_typetracer`
- adds `ak.typetracer.typetracer_with_report` that builds a typetracer array and associated report from a `Form`.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
This moves a typetracer-dependent code path out of the NumPy ufunc handling and into a generic function. I think `empty_if_typetracer` is also something that @lgray needed.

I approve this and I think it can be merged at any point, but it would be good if @lgray can tell us whether `empty_if_typetracer` is useful for his use-case or if some tweak could make it better. We're ignoring, for now, the fact that it's in a private API; everything that you use will become public API once things settle.

**Comment by agoose77** [comment]
@jpivarski would you like me to remove `empty_if_typetracer` from this PR? :)

**Comment by lgray** [comment]
Hey,

I'll be able to answer this better on Wednesday. Presently away.

**Comment by jpivarski** [comment]
No, I thought that `empty_if_typetracer` is a good addition. Good enough, actually, for @lgray's use-case as well. We can revisit this on Wednesday. (I don't see anything this PR might be blocking.)

**Comment by agoose77** [comment]
I've moved the cleanups this PR to https://github.com/scikit-hep/awkward/pull/2150. Now this is almost entirely `empty_if_typetracer`.

**Comment by agoose77** [comment]
@jpivarski I think it's time to make `typetracer_with_report` public as it's now used by Dask, and `empty_if_typetracer` should be useful for @lgray (?)

**Comment by lgray** [comment]
Can you give me a short example of how you expect it to be used?

**Comment by agoose77** [comment]
The code in coffea's lookup tools:
https://github.com/CoffeaTeam/coffea/blob/38f0fcbe96efaea75d2ddfb70bd3e0b49ffd8ddf/coffea/lookup_tools/lookup_base.py#L33-L40

can be simplified to

```python
if backend == "cpu":
    if thelookup_wref is not None:
        thelookup = thelookup_wref()
    else:
        thelookup = thelookup_dask.compute()
elif backend == "typetracer":
    thelookup = thelookup_wref()
else:
    raise AssertionError
    
zlargs = [ak.typetracer.empty_if_typetracer(x) for x in args]
result = thelookup._evaluate(
    *(list(__pre_args__) + [awkward.to_numpy(zlarg) for zlarg in zlargs]),
    **kwargs,
)
```

You can simplify this further if you clarify the `thelookup` logic.

**Comment by lgray** [comment]
I'd also like to update that to use `inspect.bind` to pack arguments instead of the clunky way I do it now. Is there a better way?

**Comment by lgray** [comment]
`thelookup` is a way to consistently and quickly get a handle to the underlying correction being applied. We made a choice that corrections always take raw numpy arrays, and we unwrap awkward for that. The switch between weakref and dask is to avoid serialization overhead in dask since otherwise dask will pickle the correction metadata, which can be very large and expensive.

i.e. it's just a pointer to a function, not an awkward array or anything like that.

**Review by jpivarski — APPROVED** [review]
Yes, these can be public now, but if the private method access breaks, we should be careful about aligning versions so that we don't have a broken Awkward + Coffea pair in the crucial period around CHEP.

**Comment by agoose77** [comment]
@lgray does this Gist help towards rewriting your transformer?

https://gist.github.com/agoose77/9fc1938bf15d1dedb0bd72a4cd501ed1

**Comment by lgray** [comment]
@agoose77 Yes! This looks very much like the correct way. I'll give it a try during one of the breaks today! TYVM!

**Comment by agoose77** [comment]
>  but if the private method access breaks, we should be careful about aligning versions so that we don't have a broken Awkward + Coffea pair in the crucial period around CHEP.

Agreed. I'll just export the symbol from `awkward.typetracer`, and we'll ensure there's a transition period.

**Comment by lgray** [comment]
Sweet - I'll try to address this in coffea before your next release since it creates incompatibility (I think?).

**Comment by agoose77** [comment]
This now doesn't rename any symbols, we only export `typetracer_with_report`, `TypeTracerReport`, and `empty_if_typetracer` functions from the public `ak.typetracer` module. So, you should make a PR, but we won't break you :)

**Pull request merged**
