### PR TITLE
Generate CUDA kernels from kernel specification

### PR DESCRIPTION
**Pull request by reikdas**
The code generator will improve with each new kernel that it can handle; and this PR will likely be a rather long one.

### CODE REVIEW

**Comment by jpivarski** [comment]
I cancelled your build so that a deployment will go out. If you need the results of this test, make another commit or ask me to start another for you (scheduled after the deployment). Thanks!

**Comment by jpivarski** [comment]
This looks good. Have you tested it on the AWS instance? That will determine if your generated "num" function is equivalent to the one Anish wrote.

**Review by jpivarski — CHANGES_REQUESTED** [review]
I just ran it on my computer and on AWS. They both fail in just one test:

```
tests-cuda/test_0345-cuda-num.py::test_num_4 FAILED                      [  7%]
```

because you're not generating `awkward_RegularArray_num_64`.

```
=================================== FAILURES ===================================
__________________________________ test_num_4 __________________________________

    def test_num_4():
        array = awkward1.Array(awkward1.layout.NumpyArray(
            numpy.array([[0.0, 1.1], [2.2, 3.3], [4.4, 5.5]])))
        cuda_array = awkward1.to_kernels(array, "cuda")
        assert awkward1.num(cuda_array, 0) == awkward1.num(array, 0)
>       assert awkward1.num(cuda_array, 1).tolist() == awkward1.num(array, 1).tolist()

tests-cuda/test_0345-cuda-num.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

array = <Array:cuda [[0, 1.1], ... 3.3], [4.4, 5.5]] type='3 * 2 * float64'>
axis = 1, highlevel = True

    def num(array, axis=1, highlevel=True):
...
>       out = layout.num(axis=axis)
E       RuntimeError: awkward_RegularArray_num_64 not found in kernels library
E       
E       (https://github.com/scikit-hep/awkward-1.0/blob/0.2.36/src/libawkward/kernel-dispatch.cpp#L87)

awkward1/operations/structure.py:202: RuntimeError
========================= 1 failed, 55 passed in 1.28s =========================
```

The build/test sequence is:

```bash
git clone --recursive https://github.com/scikit-hep/awkward-1.0.git -b reikdas/cudagen
cd awkward-1.0/
python localbuild.py --pytest tests
python dev/generate-kernelspec.py
python dev/generate-tests.py
python -m pytest -vv -rs tests-spec
python -m pytest -vv -rs tests-cpu-kernels
pip uninstall -y awkward1-cuda-kernels
pip uninstall -y awkward1-cuda-kernels
pip uninstall -y awkward1-cuda-kernels
./cuda-build.sh --install
python -m pytest -vv -rs tests-cuda
```

This is the only thing to fix. Once this passes, it will be merged.

**Comment by reikdas** [comment]
The tests should be fixed now :)

**Comment by jpivarski** [comment]
There are some compiler warnings; the generated code has some rough edges, but that's to be expected.

```
src/cuda-kernels/awkward_IndexedArray_mask.cu(15): warning: pointless comparison of unsigned integer with zero
          detected during instantiation of "void cuda_IndexedArray_mask(int8_t *, const B *, int64_t, Error *) [with B=uint32_t]" 
(81): here

src/cuda-kernels/awkward_ListArray_validity.cu(24): warning: pointless comparison of unsigned integer with zero
          detected during instantiation of "void cuda_ListArray_validity(const C *, const D *, int64_t, int64_t, Error *) [with C=uint32_t, D=uint32_t]" 
(80): here

src/cuda-kernels/awkward_ListOffsetArray_reduce_global_startstop_64.cu(12): warning: variable "thread_id" was declared but never referenced

src/cuda-kernels/awkward_ListOffsetArray_reduce_global_startstop_64.cu(12): warning: variable "thread_id" was declared but never referenced

src/cuda-kernels/awkward_UnionArray_fillna.cu(15): warning: pointless comparison of unsigned integer with zero
          detected during instantiation of "void cuda_UnionArray_fillna(int64_t *, const B *, int64_t, Error *) [with B=uint32_t]" 
(62): here

src/cuda-kernels/awkward_UnionArray_validity.cu(22): warning: pointless comparison of unsigned integer with zero
          detected during instantiation of "void cuda_UnionArray_validity(const int8_t *, const B *, int64_t, int64_t, const int64_t *, Error *) [with B=uint32_t]" 
(103): here

src/cuda-kernels/awkward_combinations.cu(12): warning: variable "thread_id" was declared but never referenced

src/cuda-kernels/awkward_combinations.cu(12): warning: variable "thread_id" was declared but never referenced
```

It also takes quite a bit longer to compile—an indication that there's a lot more code now.

But it all works! (On my computer and the AWS instance; I deleted everything and compiled from scratch.)



[cuda-kernels-written.pdf](https://github.com/scikit-hep/awkward-1.0/files/5150703/cuda-kernels-written.pdf)

**Review by jpivarski — APPROVED** [review]

**Pull request merged**
