### PR TITLE
fix: adjust checks in ForthMachine to prevent segfault when num_items is negative

### PR DESCRIPTION
**Pull request by ariostas**
This PR addresses bug that was found in #3188. For some particular file, the `num_items` variable ended up being negative and it was causing a segfault when trying to write some data. I adjusted and added some checks to prevent the segfault and make it crash gracefully. Nevertheless, it does not address the issue with reading the file in #3188.

I checked with the Compiler Explorer and both of these options produce the same machine code, so I just used the more expressive one.
```cpp
if (num_items < 0) num_items = 0;
num_items *= (num_items >= 0)
```

### CODE REVIEW

**Comment by ariostas** [comment]
Maybe to make it more complete it should set `current_error_` to some (possibly new) type of error?

**Comment by jpivarski** [comment]
> Maybe to make it more complete it should set `current_error_` to some (possibly new) type of error?

That was my first thought, since this is another thing that could go wrong. However, for some AwkwardForth [type codes](https://awkward-array.org/doc/main/reference/awkwardforth.html#input-read), it has effectively been taking the maximum of the stack-read variable and zero for a while now. Turning this into an error would make code development in AwkwardForth more developer-friendly, but most of the development that (I believe) will ever be done in this language has already been done. Its existence was motivated by accelerating Uproot TTree-reading, and as we move to RNTuple, it becomes irrelevant. In principle, it's useful for other non-columnar data formats whose types are static through the dataset but not known before reading (i.e. the type is specified in a file-bound schema). Avro is one example of that, Protobuf, and Thrift are others, maybe also Flatbuffers, but there hasn't been high demand for getting these formats into Awkward Arrays. AwkwardForth is not the best choice for fully dynamic formats (JSON, BSON, etc.) or columnar formats (Parquet), or if a JIT-compiler is available. It's fairly niche—great for the Uproot TTree use-case—but that's done.

So I'd be happy to turn the accidental interpretation of negative `num_items` as zero into an explicit rule in the language. It can be documented as a short sentence somewhere in here:

https://github.com/scikit-hep/awkward/blob/af232f545a01d06dd269d5ed16df38ec4469b30e/docs/reference/awkwardforth.rst?plain=1#L1183-L1220

For tests (for this PR), how about the following? I ran these on the old/broken AwkwardForth on Linux.

Positive `num_items`; no issues:

```python
>>> vm = awkward.forth.ForthMachine32("input source 5 source #q-> stack")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.stack
[1, 2, 3, 4, 5]
```

and

```python
>>> vm = awkward.forth.ForthMachine32("input source output sink float64 5 source #q-> sink")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.output("sink")
array([1., 2., 3., 4., 5.])
```

Negative `num_items`; some issues (but no segfault on Linux):

```python
>>> vm = awkward.forth.ForthMachine32("input source -5 source #q-> stack")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.stack
[]
```

and

```python
>>> vm = awkward.forth.ForthMachine32("input source output sink float64 -5 source #q-> sink")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.output("sink")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative dimensions are not allowed
```

Maybe these would segfault on MacOS, or maybe the segfault only happens deeper in a more complex example. But anyway, with the fix currently implemented in this PR, the first would return the same thing and the second would also return an empty array.

Actually, maybe it would be better to test a negative `num_items` followed by a positive `num_items` (or vice-versa), which are showing bad behavior on Linux. (Keep in mind that I'm not running in this PR.)

```python
>>> vm = awkward.forth.ForthMachine32("input source -5 source #q-> stack 5 source #q-> stack")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.stack
[1068248464, 3, -1170705504, 0, 49]
```

With this PR, the output should be `[1, 2, 3, 4, 5]` because the first `-5 source #q-> stack` will now be interpreted as a no-op.

```python
>>> vm = awkward.forth.ForthMachine32("input source output sink float64 -5 source #q-> sink 5 source #q-> sink")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.output("sink")
array([], dtype=float64)
```

This should also be `[1, 2, 3, 4, 5]` for the same reason.

This is clearly doing bad things in Linux because a few steps _after_ these steps, I got a core dump.

In a new process, I tested the positive `num_items` followed by negative `num_items`, and these should also both return `[1, 2, 3, 4, 5]`, which they do not (without this PR):

```python
>>> vm = awkward.forth.ForthMachine32("input source 5 source #q-> stack -5 source #q-> stack")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.stack
[1, 2, 3, 4, 5]
```

and

```python
>>> vm = awkward.forth.ForthMachine32("input source output sink float64 5 source #q-> sink -5 source #q-> sink")
>>> vm.run({"source": np.array([1, 2, 3, 4, 5])})
>>> vm.output("sink")
array([], dtype=float64)
```

**Comment by ariostas** [comment]
Thanks so much, Jim. I added the rule to the documentation and the tests you suggested. I couldn't find if the `awkward-cpp` tests should go somewhere else, so let me know if I should move them.

**Review by jpivarski — APPROVED** [review]
This all looks good and I'd say it's ready to merge!

I don't know which awkward-cpp tests you mean, but almost all of the awkward-cpp testing is done in Python through Awkward, anyway. (The major exception is the kernel-testing, but that's unrelated to AwkwardForth.) These tests are definitely sufficient.

**Comment by ariostas** [comment]
Hmm I'll have to check why some Windows tests are failing.

**Comment by ariostas** [comment]
Welp, it's the second time this week where I run into issues by not explicitly specifying `dtype`. But now it should all be good to go.

**Review by ianna — APPROVED** [review]
Looks great! Thanks!

**Comment by jpivarski** [comment]
@all-contributors please add @ariostas for code

**Pull request merged**
