### PR TITLE
Try out the allcontributors bot.

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
@all-contributors please add @jpivarski for bug, code, content, data, doc, design, example, ideas, infra, maintenance, question, review, test, tutorial, and talk.

Let's see what happens.

**Comment by jpivarski** [comment]
@all-contributors please add @nsmith- for bug, code, example, ideas, question, test, and talk.

Let's see if it can add to an existing list.

**Comment by jpivarski** [comment]
@all-contributors please add @nsmith- for bug, code, example, ideas, question, test and talk

**Comment by jpivarski** [comment]
@all-contributors please add @ianna for code, ideas, maintenance, test

**Comment by jpivarski** [comment]
@all-contributors please add @lgray for bug, code, ideas, test, and talk.

**Comment by jpivarski** [comment]
@all-contributors please add @henryiii for bug, code, ideas, infra, test, and talk.

**Comment by henryiii** [comment]
Glad to see the bot is working! I might need to look into my configuration of it.

**Comment by jpivarski** [comment]
@all-contributors please add @henryiii for bug, code, ideas, infra, test, and talk.

It's sort-of working (see, for example, [this](https://github.com/all-contributors/all-contributors-bot/issues/310)). I'm figuring out a proper way to use it, which apparently involves adding one PR _after_ the next.

**Comment by jpivarski** [comment]
@all-contributors please add @reikdas for code, ideas, talk.

**Comment by jpivarski** [comment]
@all-contributors please add @trickarcher  for code, ideas, test.

**Comment by jpivarski** [comment]
@all-contributors please add @Ellipse0934  for code, ideas, test.

**Comment by jpivarski** [comment]
@all-contributors please add @veprbl for bug, code, infra, test.

**Comment by jpivarski** [comment]
@all-contributors please add @glass-ships for code, ideas, test, talk.

**Comment by jpivarski** [comment]
@all-contributors please add @EscottC for code, ideas, test, talk.

**Comment by jpivarski** [comment]
@all-contributors please add @masonproffitt for bug, code, ideas, test, talk.

**Comment by jpivarski** [comment]
@all-contributors please add @mhedges for code, ideas, question, test, talk.

**Comment by jpivarski** [comment]
@all-contributors please add @guitargeek code, ideas, test.

**Comment by jpivarski** [comment]
@all-contributors please add @Jayd-1234 for code.

**Comment by jpivarski** [comment]
@all-contributors please add @benkrikler for code.

**Comment by jpivarski** [comment]
@all-contributors please add @bfis for code.

**Comment by jpivarski** [comment]
@all-contributors please add @douglasdavis for code.

**Comment by jpivarski** [comment]
@all-contributors please add @jpata for ideas.

**Comment by jpivarski** [comment]
@all-contributors please add @martindurant for ideas.

**Comment by jpivarski** [comment]
This PR doesn't actually make any changes. It's just a place to invoke the all-contributors bot.

Closing it now.

**Comment by jpivarski** [comment]
@all-contributors please add @gordonwatts for ideas.

**Pull request closed without merging**
