### PR TITLE
ci: lint PR titles according to conventional commits

### PR DESCRIPTION
**Pull request by agoose77**
This PR introduces a new workflow that runs on PRs:
https://github.com/amannn/action-semantic-pull-request

By default, this uses the [commitizen (angular derivative) convention](https://github.com/commitizen/conventional-commit-types):

Note that some/all of the commits in this PR use a sentence-cased variant, because that was what I was used to. The new standard is lowercase prefixes.

### CODE REVIEW

**Comment by agoose77** [comment]
Good, the checks fail for `maint:`. Now try `ci:`...

**Comment by agoose77** [comment]
@henryiii @jpivarski you both expressed an interest in this (by engaging in the discussion on Zoom)! Let me know if you are happy to merge this as-is, or want any changes.

**Review by jpivarski — APPROVED** [review]
So this one is

> Lint PR / Validate PR title (pull_request) Successful in 3s

(I was wondering what form the title test would take, since it's not a git-level thing.)

Works for me. I can make this a requirement. I'll merge this now and make it a requirement on Wednesday, since everyone with an open PR will have to merge this branch.

**Comment by jpivarski** [comment]
Although I'll give @henryiii a chance to weigh in before actually merging.

**Review by henryiii — APPROVED** [review]
Seems fine to me, we could always remove it if it doesn't work out well for us.

**Pull request merged**
