### PR TITLE
fix: flake8 F811

### PR DESCRIPTION
**Pull request by henryiii**
Starting to work on flake8 issues; this one was the most worrisome, since the five tests these shadow were never run. I'll add flake8 to pre-commit once I've fixed the issues, this one (since it runs new tests) deserved to be it's own cherry-picked PR.

Accidentally included black fixes from #652.

### CODE REVIEW

**Comment by jpivarski** [comment]
You're right; this is worrisome. I've found examples of overshadowed tests, too. I'm glad that this can now be automated.

Fortunately, it looks like they're not broken overshadowed tests (from the CI so far)!

**Comment by henryiii** [comment]
Great! (technically, it will be automated very soon, but isn't yet, at least not in CI or by the currently publicly available pre-commit file).

**Comment by jpivarski** [comment]
We should have a procedure for merging these PRs. Should I consider all non-draft PRs from you to be "ready to merge" from your perspective and when I press the merge button, I'm confirming it? That is, your PRs are passed by a consensus between the two of us. If it hasn't passed tests yet (also a precondition), I could write "ready to merge" for my vote until the auto-merge is set up.

**Comment by henryiii** [comment]
Yes, if you see a PR from me, if it's not draft, it's ready to be merged if you like it and it passes tests. If it does not pass tests, you'll often see me set it back to draft as I scramble to fix it (usually Python 2. :) ). If I'm making a placeholder or a discussion PR, it will be draft.

**Comment by jpivarski** [comment]
Thanks!

**Pull request merged**
