### PR TITLE
Broaden access to ArrayGenerator attributes in Python

### LINKED ISSUE #272: ArrayGenerator parameters
Can the following parameters used to declare `ArrayGenerator` be exposed to python: `callable`, `args`, `kwargs`?
Already `form` and `length` are available.

### PR DESCRIPTION
**Pull request by jpivarski**
This is for #272.

### CODE REVIEW

**Comment by jpivarski** [comment]
I think this fixes #272; I think it's enough to have all of these accessors on the ArrayGenerator and not the VirtualArray:

https://github.com/scikit-hep/awkward-1.0/blob/33c73c9c4e854b81b760c286431d516237508dfa/tests/test_0274-access-ArrayGenerator-in-Python.py#L13-L48

There's a strong argument for putting them on the generator, because there are two generator types accessible in Python (a Pythonized ArrayGenerator and an opaque SliceGenerator, which can't easily provide access to its slice because I have Python → C++ slice conversions but not in the other direction; that would be a big project). The `with_` methods let you change the Form and length without needing to know which type of generator you have. If it's a Pythonized ArrayGenerator, then you can change the `callable`, `args`, and `kwargs`, too.

On VirtualArray, however, there's a `generator` property that gives you the generator (regardless of its type) that you can then call `with_*` on. Having to rebuild a VirtualArray from all of its components to just replace the length might be a chunky bit of code, but it would be much easier to wrap that up in a helper function in Python than to build a full set of `with_` functions at this next level up.

Does this work for you? If so, I'll merge it immediately.

**Comment by jpivarski** [comment]
Forgot to add @nsmith- to my previous comment.

**Comment by nsmith-** [comment]
Yeah since `length` is a generator property and not a virtual array property, I think it makes sense to have `with_length` on the generator. There is not so much work to rewrap as the virtual array properties all appear accessible already. I suppose the following is sufficient:
```python
def add_length(array: awkward1.layout.VirtualArray, length: int):
    return awkward1.layout.VirtualArray(
        array.generator.with_length(length),
        array.cache,
        array.cache_key,
        array.identities,
        array.parameters,
    )
```

**Comment by nsmith-** [comment]
I checked out this branch, and ran into another issue that is familiar from awkward0: the form check upon materialization in my parent array is not happy that the expected form has `has_length=False` for some of the children nodes where the materialized one has `has_length=True`. If I'm willing to lie to awkward and give a dummy length while making the original form then it "works" but I'm not sure of the implications here.

**Comment by jpivarski** [comment]
> I checked out this branch, and ran into another issue that is familiar from awkward0: the form check upon materialization in my parent array is not happy that the expected form has `has_length=False` for some of the children nodes where the materialized one has `has_length=True`.

That, in itself, is a good argument against making the length mutable.

> If I'm willing to lie to awkward and give a dummy length while making the original form then it "works" but I'm not sure of the implications here.

The only implication is that if it is materialized before you expect it to be, there would be an error due to the dummy length being the wrong length.

I was thinking that I should weaken the constraint for you: to make `has_length` be three-valued: true, false, and "I don't care." But, thinking about it, isn't "I don't care" the same as `has_length=False`? If you have nested VirtualArrays, the outer one can have a different `has_length` than the inner one.

**Review by nsmith- — APPROVED** [review]
Works for my use case

**Pull request merged**
