### PR TITLE
fix: `ak.full_like` with unknown arrays

### PR DESCRIPTION
**Pull request by agoose77**
We already test for unknown scalars, but unknown arrays slip through! In general, this logic should test for scalar fill values in addition to whether they're known.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
Fixing `ak.full_like` should also fix `ak.ones_like` and `ak.zeros_like`, right? Because they're implemented in terms of `ak.full_like`.

If you're adding a test for `ak.full_like`, just copy-paste it for `ak.ones_like` and `ak.zeros_like` (removing the fill value) because I think they would automatically work.

**Comment by agoose77** [comment]
TODO: this should simplify into broadcasting.

**Comment by jpivarski** [comment]
Should this be `pr-on-hold` or closed?

**Comment by agoose77** [comment]
I'll close for now.

**Pull request closed without merging**
