### PR TITLE
test: sort headers in ArrayBuilder.h

### PR DESCRIPTION
**Pull request by ianna**
test if the cpp test of the ArrayBuilder is triggered.

### CODE REVIEW

**Review by ianna — COMMENTED** [review]
The non kernel tests fail on [Run Tests (pypy3.9, x64, ubuntu-latest, pypy)](https://github.com/scikit-hep/awkward/pull/2978/files#logs)

**Comment by jpivarski** [comment]
Is this no longer needed because of #2981?

**Comment by ianna** [comment]
The ArrayBuilder is tested extensively in Python. The cpp test has been removed, so I'm closing this PR.

**Review by ianna — COMMENTED** [review]
@jpivarski - the branch can be safely deleted.

**Pull request closed without merging**
