### PR TITLE
feat: add `recursive` flag to `Content.to_packed`

### LINKED ISSUE #2916: flatten / unflatten operation touches whole records
### Version of Awkward Array

master + #2912

### Description and code to reproduce

```python3
from coffea.nanoevents import NanoEventsFactory, PFNanoAODSchema
from distributed import Client
#import dask                                                                                                                                                                                                                                       
import dask_awkward as dak

import awkward as ak

import pyinstrument
import time

if __name__ == "__main__":
    client = Client()

    PFNanoAODSchema.warn_missing_crossrefs = False

    events = NanoEventsFactory.from_root(
        {"./nano_mc2017_1.root": {"object_path": "Events", "steps": [[0,40],[40, 80]]}},
        schemaclass=PFNanoAODSchema,
    ).events()

    fatjet = events.FatJet
    pf = ak.flatten(fatjet.constituents.pf, axis=2)

    unflat_pf = ak.unflatten(pf, counts=ak.flatten(ak.num(fatjet.constituents.pf, axis=2)), axis=1)

    print(dak.necessary_columns(unflat_pf.pt))

    print(unflat_pf.pt.compute())
```

results in:
```
(coffea-dev) lgray@Lindseys-MacBook-Pro coffea % python connor_repro.py
/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/structure.py:895: UserWarning: Please ensure that dask.awkward<flatten, npartitions=2>
        is partitionwise-compatible with dask.awkward<flatten, npartitions=2>
        (e.g. counts comes from a dak.num(array, axis=1)),
        otherwise this unflatten operation will fail when computed!
  warnings.warn(
{'from-uproot-f43b2959a838308afd95be4cbeebc4fb': frozenset({'PFCands_d0', 'PFCands_lostInnerHits', 'PFCands_pdgId', 'PFCands_trkChi2', 'nFatJet', 'PFCands_dz', 'PFCands_pt', 'PFCands_vtxChi2', 'FatJetPFCands_pFCandsIdx', 'PFCands_mass', 'PFCands_eta', 'nFatJetPFCands', 'nPFCands', 'PFCands_charge', 'PFCands_trkQuality', 'PFCands_d0Err', 'PFCands_dzErr', 'PFCands_puppiWeightNoLep', 'PFCands_puppiWeight', 'PFCands_phi', 'FatJet_nConstituents', 'PFCands_pvAssocQuality'})}
[[[19.9, 4.32, 5.29, 6.13, 5.61, ..., 1.33, 0.67, 0.629, 0.668, 0.459]], ...]
```

where it should only require the following columns:
```
frozenset({'nPFCands', 'FatJet_nConstituents', 'nFatJetPFCands', 'PFCands_pt', 'FatJetPFCands_pFCandsIdx', 'nFatJet'})
```

### PR DESCRIPTION
**Pull request by agoose77**
This should fix #2916, which was caused by eager recursive packing of the array layout before unflattening.

This was first discussed in https://github.com/scikit-hep/awkward/issues/910#issuecomment-860494445, where we understood that _not_ packing the layout can lead to invalid unflatten operations.

This PR fixes #2916 by introducing a `recursive: bool = True` argument to `Content.to_packed()`. This allows us to perform a single-layout packing, which ensures that nodes below the current node are left untouched, reducing the numbers of buffers required at runtime.

I'm not 100% sure if this is the _right_ API to go with. I _think_ talking about packing non-recursively makes sense, rather than as a shoehorned bugfix. But, @jpivarski if you think otherwise let me know!

### CODE REVIEW

**Comment by lgray** [comment]
@cmoore24-24 Please check this out in your full analysis and see if it fixes things correctly in-situ. If the problem remains we'll have to understand if it's still the same issue and fix it in this PR or if it's a new issue altogether. (use awkward@main with this merged in)

**Comment by lgray** [comment]
Ah, indeed I can see a few work arounds. I'll confirm one in an hour or so.

**Review by jpivarski — APPROVED** [review]
Adding a `recursive: bool = True` argument is definitely a good API.

We're just waiting for @cmoore24-24 to test it, and then I'd like to merge it to make a new awkward release. @agoose77, is there anything else you want to add before merging?

**Comment by jpivarski** [comment]
From @lgray: let's merge this now and make a new release. If @cmoore24-24 encounters any problems, they'll be filed as new issues.

**Comment by cmoore24-24** [comment]
Sorry for the delay and glad that this was merged; it has been entirely fixed in my full analysis. Thank you all for the help!

**Pull request merged**
