### PR TITLE
Doxygen Documentation of GrowableBuffer and LayoutBuilder.

### PR DESCRIPTION
**Pull request by ManasviGoyal**
This PR contains the doxygen documentation of -
- [x] GrowableBuffer
- [x] LayoutBuilder
- [x] utils.h

There are also some minor fixes in the code of LayoutBuilder and its tests.

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@jpivarski I have separated the doxygen documentation from PR #1574 so that it can be merged. I'll add sphinx documentation in that once I clarify some things from Angus once he is back.

How can I view the doxygen documentation? Just wanted to make sure that the links to the classes and methods work.

**Comment by jpivarski** [comment]
> How can I view the doxygen documentation? Just wanted to make sure that the links to the classes and methods work.

With doxygen installed (I get it from conda-forge, but you can get it from anywhere), this command will do it:

```bash
doxygen docs-doxygen/Doxyfile
```

and the output will go in some new subdirectory of `docs-doxygen` (`_build`?).

It probably won't find your file, because it's in a different subdirectory.

...

Or maybe it will? I don't see anything in [Doxyfile](https://github.com/scikit-hep/awkward/blob/main/docs-doxygen/Doxyfile) that specifies which directories the C++ code can be found in. It might be searching everything recursively from `.`, in which case, your header-only files will be found.

**Comment by ManasviGoyal** [comment]
> It probably won't find your file, because it's in a different subdirectory.

@jpivarski I tried it and yes it is not able to find these files. Is there any alternative to check?

**Comment by jpivarski** [comment]
I just searched the Doxygen documentation, and it looks like it's in the `INPUT` setting:

https://github.com/scikit-hep/awkward/blob/9e17f2955670b1e63e684da7c4ad4c835a9994e6/docs-doxygen/Doxyfile#L832-L833

This one is looking in the `include` directory (with one extra file to be found in `docs-doxygen/input.md`, the landing page), so you'd have to add to this list the path to the headers within `src/awkward/_v2/cpp-headers`.

**Comment by ManasviGoyal** [comment]
@jpivarski The documentation is generating correctly now. Please check and let me know if anything needs to be fixed or else we can merge it.

**Review by jpivarski — APPROVED** [review]
I just checked out this branch, built the Doxygen, and clicked through all the pages. It looks great!

I'll merge it now. Thanks, and nice job!

**Pull request merged**
