### PR TITLE
`to_rdataframe` extensive tests and bug fixes

### PR DESCRIPTION
**Pull request by ianna**
- generate `RVec`s when requested that fixes issue #1477
- `RVec` namespace correction
- add tests

### CODE REVIEW

**Comment by ianna** [comment]
This closes https://github.com/scikit-hep/awkward/issues/1477

**Comment by ianna** [comment]
@jpivarski - please, have a look when you have time. Thanks!

**Comment by ianna** [comment]
@jpivarski - please, check when you have time. Thanks!

**Review by jpivarski — APPROVED** [review]
These all look like appropriate changes to me! In some cases, I can see that they were definitely needed, such as `ROOT::RVec` → `ROOT::VecOps::RVec`, having the `entry_type` depend on `flatlist_as_rvec`, and many `layouts` depend on `[key]`. The tests appear to be exhaustive. Please do squash-and-merge!

**Pull request merged**
