### PR TITLE
fix: add `Record.copy`

### LINKED ISSUE #1995: ak.record.Record does not have a `copy` method
It should have one for consistency with the ak.contents.Content subclasses, even though it can't be duck-typed with them (ak.record.Record doesn't have any of the arguments that ak.contents.Content have, and vice-versa).

### PR DESCRIPTION
**Pull request by agoose77**
I haven't added any tests, because we probably need to revisit our `copy` tests anyway (this code has been touched a reasonable amount)

### CODE REVIEW

**Comment by jpivarski** [comment]
I guess I should have been clearer in the issue. (I wrote it quickly, while trying to not lose track of something else.)

The `Content` subclass's `copy` methods take all the same arguments as the corresponding `__init__`, but with `unset` as the default. They construct a new (shallow copy) instance with only the not-`unset` arguments replaced.

Maybe a better name would have been "copy except for..." but it's already past 2.0.0 and now [it's being used in fastjet](https://github.com/scikit-hep/fastjet/pull/156).

The `Content.copy` doesn't have a top-level protocol because each subclass has a different set of arguments.

**Comment by agoose77** [comment]
@jpivarski yes, right - this wasn't supposed to be up for review yet ... too many PRs open at once :laughing:

**Review by ioanaif — APPROVED** [review]
This follows the implementation in `contents` so it looks correct.  However, I am not aware of the `issue` Jim mentions.

**Comment by agoose77** [comment]
Ah good point, I should link that here.

**Pull request merged**
