### PR TITLE
docs: Fixed typo in ak.argsort page

### PR DESCRIPTION
**Pull request by Laurits7**
Found a typo in the docs. In the example it should be "data" not "index"

### CODE REVIEW

**Comment by Laurits7** [comment]
@jpivarski

**Comment by agoose77** [comment]
Thanks @Laurits7, this looks like a bug, and the correct fix :)

**Review by jpivarski — APPROVED** [review]
Thanks!

**Comment by jpivarski** [comment]
@all-contributors please add @Laurits7 for docs

**Pull request merged**
