### PR TITLE
feat!: don't broadcast `EmptyArray` in `broadcast_and_apply`

### PR DESCRIPTION
**Pull request by agoose77**
Currently, we're too eager to convert `EmptyArray`s into known `NumpyArray`s. This PR starts the process of unwinding this, making `ak.broadcast_arrays` preserve the unknown array.

The planned existence of `ak.enforce_type` should ensure that we can deprecate this logic (in this PR), so that e.g. ufunc operations on unknown arrays throw warnings.

At a high level, we should permit `EmptyArray`s instead of `NumpyArray`s where it is not required that the programmer choose an arbitrary dtype. i.e., if the code requires a boolean dtype, it can accept an `EmptyArray`, whereas if the code supports many dtypes (reducers) it fails.

### CODE REVIEW

**Comment by jpivarski** [comment]
We now have an `ak.enforce_type`. Can this PR be closed?

**Comment by agoose77** [comment]
I think the contrary; we want to be stricter now that it's easier to remove unknown arrays through `enforce_type`.

**Comment by jpivarski** [comment]
So `EmptyArray` would not be allowed to broadcast with `NumpyArray` at all? Even though someone could reassign `EmptyArray`, that sounds inconvenient. (Broadcasting is only ever about convenience.)

**Comment by agoose77** [comment]
Rather that it won't be coerced during broadcasting. This PR name should really imply that broadcasting won't handle unknown arrays, just as it doesn't handle NumPy arrays.

**Comment by jpivarski** [comment]
So the broadcasting logic can be simplified by just removing the `EmptyArray` case? That sounds good! But it would probably be easier to start over, rather than bring this PR up-to-date, right?

**Pull request closed without merging**
