### PR TITLE
corrected the class names in documentation

### PR DESCRIPTION
**Pull request by ianna**
@jpivarski - I've noticed the name mismatch when looking at the links you've posted on Slack.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
That's right: this was an uncaught copy-paste error. Thanks for catching it!

**Comment by jpivarski** [comment]
(Auto-merge is on, so this will be merged as soon as the tests pass. It will stop if any fall or if you commit something else before it's done.)

**Review by ianna — COMMENTED** [review]
@jpivarski - it looks like the auto merge waits for the tests that will never run for this PR since the changes are only in documentation.

**Comment by jpivarski** [comment]
Ah, I see. Nothing works as well as planned.

**Pull request merged**
