### PR TITLE
argsort bugfix for empty arrays

### PR DESCRIPTION
**Pull request by ianna**
address issue #811

### CODE REVIEW

**Comment by lgray** [comment]
Cool - I'll try this out momentarily.

**Review by jpivarski — APPROVED** [review]
Yes, if the length is zero, `ak.argsort` should not be returning a copy of the input array, as this won't have integer type. The method you have of creating an empty NumpyArray should work, though this should too:

```python
return NumpyArray(Index64(0))
```

which would allocate nothing, rather than one element that isn't viewed.

But now it has me wondering if Indexes and NumpyArrays with no allocation (their array is a `nullptr`, pointing at the `0` address in memory) are correctly converted to NumPy arrays. It would be weird if there were any issues with that, as we've been using that technique for so long in so many places and never encountered any problems with it. I ought to do a test.

**Comment by lgray** [comment]
Hmm hold on, still getting the same error despite rebuilding with this patch.

**Comment by lgray** [comment]
OK - that was my fault, stale install. Looks good. Let me test one more thing.

**Comment by ianna** [comment]
> Yes, if the length is zero, `ak.argsort` should not be returning a copy of the input array, as this won't have integer type. The method you have of creating an empty NumpyArray should work, though this should too:
> 
> ```python
> return NumpyArray(Index64(0))
> ```
> 
> which would allocate nothing, rather than one element that isn't viewed.
> 
> But now it has me wondering if Indexes and NumpyArrays with no allocation (their array is a `nullptr`, pointing at the `0` address in memory) are correctly converted to NumPy arrays. It would be weird if there were any issues with that, as we've been using that technique for so long in so many places and never encountered any problems with it. I ought to do a test.

yes, this works and is shorter:
```python
      return std::make_shared<NumpyArray>(Index64(0));
```

**Comment by lgray** [comment]
OK - another test on a different file fails for a different reason now. :-)

I'll post another issue once I get to the bottom of that.

**Comment by lgray** [comment]
Please go ahead, merge, and mint an rc so I can test this over the whole input fileset.

**Comment by ianna** [comment]
> Please go ahead, merge, and mint an rc so I can test this over the whole input fileset.

Thanks! I'll do it as soon as the tests pass. Looking forward to seeing a new issue ;-)

**Pull request merged**
