### PR TITLE
[DO NOT MERGE] Diff that fixes ak.from_parquet column selection

### LINKED ISSUE #1606: `ak.from_parquet` returns empty array when columns are specified
### Version of Awkward Array

HEAD

### Description and code to reproduce

```python
>>> taxi = ak.from_parquet(
    "https://pivarski-princeton.s3.amazonaws.com/chicago-taxi.parquet",
    columns=["trip.km"],
)
>>> taxi.type.show()
7728 * {
    
}

```

### PR DESCRIPTION
**Pull request by douglasdavis**
This diff fixes #1606 with the chicago taxi dataset, but perhaps this is not a general fix. cc @jpivarski @agoose77 @martindurant

### CODE REVIEW

**Comment by agoose77** [comment]
@douglasdavis thanks for filing this. On the face of it, our two PRs (#1619) look very similar. Yet, mine segfaults. Could you try the test in #1619 and see what happens here?

**Comment by douglasdavis** [comment]
sure! just used that test in #1619 and it passed with this patch

**Comment by agoose77** [comment]
Ah, I updated it to remove the crash.

I tried this on your PR and it also breaks, which reassures me we're hitting the same bug:
```python
import os
import awkward as ak

def test_extension(tmp_path):
    array = ak._v2.Array(
        [
            [
                {"x": 1, "y": 1.1},
                {"x": 2, "y": 2.2},
                {"x": 3, "y": 3.3},
            ],
            [
                {"x": 1, "y": 1.1},
                {"x": 2, "y": 2.2},
            ]]

    )
    path = os.path.join(tmp_path, "array-ext.parquet")

    ak._v2.to_parquet(array, path, extensionarray=True)

    result = ak._v2.from_parquet(path, columns=["x"])
    # assert result.fields == ["x"]

test_extension("/tmp")
```

**Comment by agoose77** [comment]
I'm going to close this, as I think we've solved it in #1619! :crossed_fingers:

**Pull request closed without merging**
