### PR TITLE
fix: failing tests after #2877

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Just noticed that a few changes in #2877 are making the cuda tests fail. So I have fixed them.

### CODE REVIEW

**Comment by ianna** [comment]
@ManasviGoyal - could you, please, run the linter and fix the warnings? Thanks!

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal - could you, please, run the linter and fix the warnings? Thanks!

I think we need to update the `py.version` to `3.8` in `pyproject.toml` to support `typing.final`. Should I go ahead and go it?

**Comment by ianna** [comment]
> > @ManasviGoyal - could you, please, run the linter and fix the warnings? Thanks!
> 
> I think we need to update the `py.version` to `3.8` in `pyproject.toml` to support `typing.final`. Should I go ahead and go it?

why is suddenly failing? what was changed?

**Comment by agoose77** [comment]
@ManasviGoyal is right that we should bump the PyLint Python version. I'd missed that when we last updated our Python bounds. I'm not sure why PyLint suddenly started noticing, though. I think we can safely assume that it's a strictness update on their part being pulled in via CI. No need to dig into it, though - we clearly should correct this on our side.

**Comment by agoose77** [comment]
@ManasviGoyal don't worry about pylint here - I'll fix it in a new PR.

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal don't worry about pylint here - I'll fix it in a new PR.

Thanks!

**Comment by ManasviGoyal** [comment]
@ianna I think this can be squash and merged now, right?

**Pull request merged**
