### PR TITLE
test: only run test for specific Numba version

### LINKED ISSUE #2878: `test_numba_ufunc_legacy` fails with `TypeError: return type must be specified for object mode`
### Version of Awkward Array

2.5.1rc1

### Description and code to reproduce

The `tests/test_2799_numba_ufunc_resolution.py::test_numba_ufunc_legacy` test fails with `TypeError: return type must be specified for object mode` 

```python
% python
Python 3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.24.3'
>>> import numba
>>> numba.__version__
'0.57.0'
>>> import awkward as ak
>>> ak.__version__
'2.5.1rc1'
```

### LINKED ISSUE #2920: All deprecations should be finalized now; no deprecations are (currently) pending
### Version of Awkward Array

HEAD

### Description and code to reproduce

```bash
% fgrep -r 'deprecate(' src/awkward | fgrep -v 'def deprecate'
src/awkward/forms/emptyform.py:            deprecate(
src/awkward/forms/form.py:            deprecate(
src/awkward/forms/form.py:            deprecate(
src/awkward/forms/numpyform.py:        deprecate(
src/awkward/contents/numpyarray.py:        deprecate(
src/awkward/contents/emptyarray.py:        deprecate(
```

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #2878

### CODE REVIEW

**Comment by agoose77** [comment]
Depends upon fixing #2920

**Comment by jpivarski** [comment]
Since the fix in this PR is also a blocker for #2920 (mutual blockers), I'll fix #2920 here in this branch. I don't think you're actively working on it or have unmerged local changes, but let me know if I'm wrong.

**Comment by jpivarski** [comment]
Well, this error is different. Didn't we see it before? Is it getting a version of pyarrow that has a bug in one of its string functions?

<details>
<pre>
']] != [['', '→δε←', '', ''], ['', 'ζz', 'zζ', '', ''], ['', 'abc', '', '']]
2024-01-10T21:03:55.4542990Z E         Full diff:
2024-01-10T21:03:55.4543300Z E           [
2024-01-10T21:03:55.4543730Z E            [['', 'αβγ', '', ''], ['', '', '']],
2024-01-10T21:03:55.4544150Z E            [],
2024-01-10T21:03:55.4545310Z E         -  [['', '→δε←', '', ''], ['', 'ζz', 'zζ', '', ''], ['', 'abc', '', '']],
2024-01-10T21:03:55.4545960Z E         ?                                                                ^^^^
2024-01-10T21:03:55.4546680Z E         +  [['', '→δε←', '', ''], ['', 'ζz', 'zζ', '', ''], ['', 'abc', ' ']],
2024-01-10T21:03:55.4547240Z E         ?                                                                ^
2024-01-10T21:03:55.4547680Z E           ]
2024-01-10T21:03:55.4547850Z 
2024-01-10T21:03:55.4547860Z 
2024-01-10T21:03:55.4548660Z tests/test_2616_use_pyarrow_for_strings.py:932: AssertionError
2024-01-10T21:03:55.4549100Z 
2024-01-10T21:03:55.4549510Z ---------- 
</pre>
</details>

**Comment by agoose77** [comment]
@jpivarski yes, that's a flaky test on MacOS. I reported it to PyArrow IIRC, but it's not exactly easy to find a reproducer! It seems to only happen on one MacOS test _sometimes_.

I'm re-running the test job that failed.

**Pull request merged**
