### PR TITLE
feat: Allow interoperability with numpy 2.x

### LINKED ISSUE #2936: Test against NumPy 2.0
Ruff has tools for this, and there are NumPy 2.0 prereleases (or there will be soon).

### PR DESCRIPTION
**Pull request by tcawlfield**
We would like to allow awkward to work correctly with numpy 2.x.

### CODE REVIEW

**Comment by jpivarski** [comment]
I'll review it when it's done. (We use the "request review" button as a way to get my attention to review it when it's time to decide if it can be merged as-is or needs changes. The "ready for review" button doesn't send me an email, but "request review" does.)

**Comment by jpivarski** [comment]
@ManasviGoyal, (real?) errors in these two kernel tests are being caught by NumPy 2.0, and not by 1.x: 2bcb015a2f21496d485ec88c3e65a8a55618fd83

**Review by jpivarski — APPROVED** [review]
Approved! We pair-programmed on Zoom.

**Comment by rgommers** [comment]
Great to see this! I'm making a compatibility overview for numpy 2.0; can I ask what version of Awkward Array this will land in?

**Comment by jpivarski** [comment]
Awkward 2.6.3, which is waiting on one more fix from #3068. I _hope_ it will be done today.

**Comment by jpivarski** [comment]
@rgommers, Awkward Array 2.6.3 ([GitHub](https://github.com/scikit-hep/awkward/releases/tag/v2.6.3), [PyPI](https://pypi.org/project/awkward/2.6.3/)) has been released with NumPy 2.0 support.

**Comment by rgommers** [comment]
Awesome, thanks @jpivarski.

**Pull request merged**
