### PR TITLE
ak.Array and ak.Record constructors. Maybe the `ak.zip` function.

### PR DESCRIPTION
**Pull request by jpivarski**
Copied from https://github.com/scikit-hep/awkward-1.0/issues/156#issuecomment-597366071

   * [X] The `ak.Array` and `ak.Record` constructor bugs (iterating over the dict keys and implementing that FIXME)
   * [x] Make `fromiter` iterate over `py::array` (mentioned in #146)
   * [ ] ~~Possibly, but not necessarily, `ak.zip` (described in #77).~~

I'm going to do `ak.zip` in a separate PR because this one has some bug-fixes.

### CODE REVIEW

**Comment by jpivarski** [comment]
@tamasgal

```python
ak.Record({"x": 1, "y": 2.2})
```

now produces a record and

```python
ak.Array({"x": 1, "y": 2.2})
```

raises an error. `ak.Array` and `ak.Record` are mutually exclusive and each error message points you to the other class.

**Comment by jpivarski** [comment]
```python
array = awkward1.Array([numpy.array([1, 2, 3]), numpy.array([4, 5, 6, 7])])
assert str(awkward1.typeof(array)) == "2 * var * int64"
assert awkward1.tolist(awkward1.tolist(array)) == [[1, 2, 3], [4, 5, 6, 7]]
```

The implementation is cheap: when we encounter a `py::array` in `fromiter`, we call `tolist()` on it and deal with it as an iterable. The numbers it contains have `numpy.integer`, `numpy.floating`, and `numpy.bool_` type (which aren't the same as Python `int`, `float`, and `bool`, which is an annoyance when converting to JSON as well!), so these are now recognized and converted as well.

A better implementation might avoid converting NumPy arrays into Python lists and iterate over it in C++, but we're just establishing behavior here; optimizing later.

At least I sorted the type checks to put the most common first. The NumPy type checks have to `import numpy`, so they're last.

**Comment by jpivarski** [comment]
Can't sort the type checks arbitrarily, or else `True`/`False` might be recognized as `int` and `bytes` as `str`.

**Comment by tamasgal** [comment]
That was quick, as always! Thanks I'll test tomorrow 😃

**Comment by jpivarski** [comment]
That last commit also removes a "skip" from the all-important "Numba cpointers" test (#118) and revealed a few other places where `awkward1._numba` had to be changed to `awkward1._connect._numba`. Thus, I have to merge this PR to make master fully work with Numba. I want to do that as soon as these tests pass; `ak.zip` can go in later.

**Pull request merged**
