### PR TITLE
feat: extend parameter coalescence to ignore transparent layouts

### PR DESCRIPTION
**Pull request by agoose77**
This PR goes towards fixing #1041, but requires some policy decisions about parameters. Originally, it added `dimension_parameters`; a tree-visiting mechanism for merging parameter dictionaries between layouts of the same dimension. @jpivarski then pointed out that we really care more about the _type_ in most cases, as that is the user-visible aspect of layouts.

This PR should do the following:
- [ ] Add a mechanism for retrieiving attribute(s) that coalesces the intra-dimension parameter(s) according to a policy 
- [ ] Change `Content.mergeable`, `Content.layout_equal`, `arrayclass()` etc. to use this API instead of inspecting single-layout parameter dictionaries, or special cased `purelist_XXX`
- [ ] Document the policy types so that we can refer to them in future.

## Policies
| Node Type | Pure List                 | Same Type                 |
|-----------|---------------------------|---------------------------|
| Option    | Merge with content        | Only ours                 |
| Indexed   | Merge with content        | Merge with content        |
| List      | Merge with content        | Only ours                 |
| Union     | Merge contents*, and ours | Merge contents*, and ours |
| Record    | Only ours                 | Only ours                 |
| Leaf      | Only ours                 | Only ours                 |

Practically speaking, we'll likely implement this as members of the `Form` types. Therefore, the word "policy" could mean a family of methods `_parameters_same_type, _parameters_pure_list`, or an enum that is switched upon. In fact, it could also be both, e.g a high-level enum that dispatches the correct family of methods. This is an aside for now.

Related issues:
- https://github.com/scikit-hep/awkward/issues/1685
- https://github.com/scikit-hep/awkward/issues/1686

### CODE REVIEW

**Comment by jpivarski** [comment]
I think you might have meant

```python
>>> import awkward as ak
>>> type(ak.Array(["hi", "bye"]))
<class 'awkward.behaviors.string.StringBehavior'>
>>> type(ak.Array(["hi", "bye"]).mask[[True, False]])
<class 'awkward.highlevel.Array'>
```

But this is, in fact, what we want. Behaviors can only be applied when a node with a given parameter is at top-level: the behavior class that one writes for type `T` is not applicable to type `option[T]`. If we were to ignore the distinction (for just option-type, say), then behavior classes would always have to be written in such a way that their `self` might be option-type or might not be option-type.

Hmmm. If the top-level node is IndexedArray (which does not change type), then the behavior should be applicable. Maybe we'd want the `arrayclass` helper function to "see through" IndexedArray.

And maybe it's time to define more behavior syntax rules, like

```python
ak.behavior["?", "RecordName"] = PossiblyMissingRecords
```

to say that it's allowed to "see through" option-type nodes.

--------------

In general, `dimension_parameters` sounds like a great idea—we were inching toward this with all of the "purelist" stuff. I followed your enumeration of rules and agree that those represent a meaningful way to "see through" certain nodes that are supposed to be invisible.

**Comment by agoose77** [comment]
Your framing of this issue in terms of the user-visible _type_ greatly clarifies what I _think_ is the direction that we need to take. As far as users are concerned, only the type matters, so it _sounds_ like we actually want something more like 
```python
@property
def type_parameters(...):
    ...
```

I will update the rules table to reflect the type-dependence over dimension.

This raises the question - when do we want `dimension_parameters` rather than `type_parameters`? 

I deliberately did not implement anything like `dimension_parameter` yet because it would lead to a lot of duplication.  Maybe we want a `policy` argument that determines how deep the `parameters_for_policy()` and `parameter_for_policy()` lookups go. We'd still want these two functions for performance.

**Comment by agoose77** [comment]
Although we recently dropped support for behavior classes that were specified for a singular array, `".", "Point"`, it's possible that we might add more to this effect in future. To my mind, the routine that checks whether this condition applies would naturally be implemented as a special policy for `parameter` / `parameters`, i.e. descend through a single additional list node. We might want to be mindful of that when designing this interface.

**Comment by agoose77** [comment]
I'm closing this for now; it's not the highest priority, and might need some rethinking in light of recent work.

**Pull request closed without merging**
