### PR TITLE
Fix: drop parameters for flattened RecordArray

### PR DESCRIPTION
**Pull request by agoose77**

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
That's looking good. The examples I wrote in Gitter could be used as a test.

```python
>>> import awkward as ak
>>> from awkward._v2.tmp_for_testing import v1_to_v2
>>> stuffy = ak.Array([{"x": [[1, 2], []]}, {"x": []}, {"x": [[3]]}], with_name="Stuff")
>>> stuffy
<Array [{x: [[1, 2], []]}, ... {x: [[3]]}] type='3 * Stuff["x": var * var * int64]'>

>>> ak.flatten(stuffy, axis=2)
<Array [{x: [1, 2]}, {x: []}, {x: [3]}] type='3 * {"x": var * int64}'>

>>> stuffy_v2 = ak._v2.highlevel.Array(v1_to_v2(stuffy.layout))
>>> stuffy_v2
<Array [{x: [[1, 2], []]}, {...}, {x: [[3]]}] type='3 * Stuff[x: var * var *...'>

>>> ak._v2.highlevel.Array(stuffy_v2.layout.flatten(axis=2))
<Array [{x: [1, 2]}, {x: []}, {x: [3]}] type='3 * Stuff[x: var * int64]'>

>>> another = ak.Array([[{"x": 1}, {"x": 2}], [], [{"x": 3}]], with_name="Stuff")
>>> another
<Array [[{x: 1}, {x: 2}], [], [{x: 3}]] type='3 * var * Stuff["x": int64]'>

>>> ak.flatten(another, axis=1)
<Array [{x: 1}, {x: 2}, {x: 3}] type='3 * Stuff["x": int64]'>

>>> ak._v2.highlevel.Array(v1_to_v2(another.layout).flatten(axis=1))
<Array [{x: 1}, {x: 2}, {x: 3}] type='3 * Stuff[x: int64]'>
```

**Comment by agoose77** [comment]
Ha, thanks for the test cases. I only added a tiny test for the draft, this makes things a lot easier.

**Comment by jpivarski** [comment]
It's set to auto-merge.

**Comment by jpivarski** [comment]
I bet the MacOS failure was due to the segfault issue (#1209), which is fixed in main, so I brought that up-to-date.

Also, this almost downgraded pybind11—you'd be the third to do that or almost do that. (See https://github.com/scikit-hep/awkward-1.0/pull/1223!)

It's looking good now, so I'm going to auto-merge again.

**Pull request merged**
