### PR TITLE
Create stubs for the `flatten` operation.

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
@ianna I just finished some major structural and name changes (which could be hard to merge against if I had left them for later) and now I'm going to put in some stubs for the `flatten` operation, as an indication of how to get started on this. I hope to have it ready for you early next week.

**Comment by ianna** [comment]
> @ianna I just finished some major structural and name changes (which could be hard to merge against if I had left them for later) and now I'm going to put in some stubs for the `flatten` operation, as an indication of how to get started on this. I hope to have it ready for you early next week.

@jpivarski - would you like me to commit the code to this PR?

**Comment by jpivarski** [comment]
Do you have code (somewhere offline)?

Either we could collaborate on this PR, or (probably better) I could use it to make the stubs, close it off, and you could start a new PR on top of it with the implementations that fill the stubs.

**Comment by jpivarski** [comment]
If you have some time today, maybe I can set up these stubs in a collaborative call, so that I can talk you through what needs to be added and why. I'll be able to start as early as 7:30am U.S. Central time, maybe 8am.

**Comment by ianna** [comment]
> If you have some time today, maybe I can set up these stubs in a collaborative call, so that I can talk you through what needs to be added and why. I'll be able to start as early as 7:30am U.S. Central time, maybe 8am.

Yes, let's try this

**Pull request merged**
