### PR TITLE
Add the beginning of an example of templated LayoutBuilder.

### PR DESCRIPTION
**Pull request by jpivarski**
This is for @ianna and @ManasviGoyal. (It's what I showed in our meeting.)

### CODE REVIEW

**Comment by ianna** [comment]
@jpivarski - shall the `GrowableBuffer.h` be placed in `src/awkward/` or `src/awkward/growable_buffer/` directory?

**Comment by ianna** [comment]
@jpivarski - shall the `GrowableBuffer.h` be placed in `src/awkward/` or `src/awkward/growable_buffer/` directory?

**Comment by ianna** [comment]
@jpivarski - shall the `GrowableBuffer.h` be placed in `src/awkward/` or `src/awkward/growable_buffer/` directory?

**Comment by jpivarski** [comment]
How about

  * `src/awkward/cpp-headers/GrowableBuffer.h`
  * `src/awkward/cpp-headers/LayoutBuilder.h`

The use of a hyphen would be a bad idea if this would ever contain Python code (it won't). It should be a generic name, to allow for other header-only additions in the future. Maybe `include` would make sense, but we already have an `include/awkward` at top-level, and I think having two of them with similar function (containing C++ header files) would be confusing. Maybe all of the headers should eventually go into here, but only if the C++ code itself becomes header-only.

After dropping v1, we could entertain the notion of converting the remaining C++ code into header-only and having the .cpp part be nothing more than template instantiations and pybind11 wrappers. The reason we _didn't_ do that before is because it increases the compilation time (with localbuild.py, we can edit .cpp files and only recompile what we change, not the whole codebase), but that becomes less relevant when the v1 C++ code is dropped (see https://github.com/scikit-hep/awkward/issues/503#issuecomment-1106750209).

**Comment by ianna** [comment]
> How about
> 
> * `src/awkward/cpp-headers/GrowableBuffer.h`
> * `src/awkward/cpp-headers/LayoutBuilder.h`
> 
> The use of a hyphen would be a bad idea if this would ever contain Python code (it won't). It should be a generic name, to allow for other header-only additions in the future. Maybe `include` would make sense, but we already have an `include/awkward` at top-level, and I think having two of them with similar function (containing C++ header files) would be confusing. Maybe all of the headers should eventually go into here, but only if the C++ code itself becomes header-only.
> 
> After dropping v1, we could entertain the notion of converting the remaining C++ code into header-only and having the .cpp part be nothing more than template instantiations and pybind11 wrappers. The reason we _didn't_ do that before is because it increases the compilation time (with localbuild.py, we can edit .cpp files and only recompile what we change, not the whole codebase), but that becomes less relevant when the v1 C++ code is dropped (see [#503 (comment)](https://github.com/scikit-hep/awkward/issues/503#issuecomment-1106750209)).

How about 
 * `src/awkward/interface/GrowableBuffer.h`
* `src/awkward/interface/LayoutBuilder.h`

**Comment by jpivarski** [comment]
What's the reasoning behind the word "interface"?

Traditionally, .h files only describe interfaces, with the implementations in .cpp files, but the idea of a header-only library is that the implementation is included in the .h file (for downstream convenience). Since this directory is only for header-only libraries (which have to be shipped in the Python module, so that they can be used by Cling at runtime), this traditional use of "interface" for .h files would be misleading. It's the opposite of that: they're only mixing interface with implementation.

Were you thinking of "interface" in a different context?

**Comment by ianna** [comment]
> What's the reasoning behind the word "interface"?
> 
> Traditionally, .h files only describe interfaces, with the implementations in .cpp files, but the idea of a header-only library is that the implementation is included in the .h file (for downstream convenience). Since this directory is only for header-only libraries (which have to be shipped in the Python module, so that they can be used by Cling at runtime), this traditional use of "interface" for .h files would be misleading. It's the opposite of that: they're only mixing interface with implementation.
> 
> Were you thinking of "interface" in a different context?

I think, I'm influenced by CMSSW. Originally, it seemed odd to use `interface` directory, but, we do include an interface to...
```c++
#include "DataFormats/TrackerCommon/interface/TrackerTopology.h"
```

**Comment by jpivarski** [comment]
> ```c++
> #include "DataFormats/TrackerCommon/interface/TrackerTopology.h"
> ```

Those really are interfaces: the implementation of TrackerTopology is in a different file. This directory is to contain only header-only code; that's why it needs to be in this directory instead of `include/awkward`.

**Comment by jpivarski** [comment]
The tests got stuck, but these are just new files in the `studies` directory—the tests are irrelevant.

**Pull request merged**
