### PR TITLE
Fixes #162. Replaces all Raw Pointer Access with wrappers.

### LINKED ISSUE #162: Layer 3 C++ code must never directly access Index.ptr, NumpyArray.ptr, or RawArray.ptr contents
Right now, there seem to be no exceptions to the rule that layer 3 (i.e. libawkward.so, as opposed to libawkward-cpu-kernels.so) code never _iterates_ over the raw buffers, but there are a few isolated cases where it accesses the first or last element. These have to be turned into kernels (albeit trivial ones) because when the buffers are hosted on a GPU, any direct access would cause a segmentation fault.

This can be done in a visual inspection sweep over the code—it wouldn't take longer than an afternoon. Suspicious cases look like

```c++
offsets_.get().ptr()[0]      // (first)
```

or

```c++
offsets_.get().ptr()[offsets_.length() - 1]      // (last)
```

Some are assignments:

```c++
offsets_.get().ptr()[0] = 0;
```

They should all be centralized in `Index` methods, like `Index::getitem_at_nowrap` and those methods should call the kernels.

### PR DESCRIPTION
**Pull request by jpivarski**
I'm adopting PR #164 into a new PR to make it possible to run Azure CI on it.

### CODE REVIEW

**Comment by jpivarski** [comment]
It's started: https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=1643&view=results

If there isn't an easier way to do this, I'll have to rethink the process. @henryiii, did you know that Azure won't trigger (and can't be manually triggered) on fork PRs? I had to make this a branch on the main repo to get it to work.

**Comment by jpivarski** [comment]
Close this duplicate PR. The CI is working on the original PR, and that's the one I'd like to merge, given the choice.

**Comment by henryiii** [comment]
I think this just changed a few days ago, and now you have to add an explicit request for a PR build. I just had someone fix this in CLI11.

**Comment by henryiii** [comment]
Okay, looks like you explicitly mention PRs in the test file. It should be fine, you might be seeing hiccups in Azure starting.

**Pull request closed without merging**
