### PR TITLE
Drop Win32 Py3.10 test and musllinux in deployment.

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
@henryiii I've added skips to pyproject.toml based on what I saw in boost-histogram: https://github.com/scikit-hep/awkward-1.0/pull/1212/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by henryiii** [comment]
I think this looks fine. Can you trigger a build without a release to see if the build passes?

**Comment by jpivarski** [comment]
I think I got that started: https://github.com/scikit-hep/awkward-1.0/actions/runs/1678746604

**Comment by jpivarski** [comment]
This one failed and I don't even see an error message: https://github.com/scikit-hep/awkward-1.0/runs/4765296804?check_suite_focus=true

**Comment by henryiii** [comment]
It's a segmentation fault:

```
 work/awkward-1.0/awkward-1.0/tests/v2/test_0404-array-validity-check.py . [ 70%]
  .............Fatal Python error: Segmentation fault
  
  Current thread 0x0000000113a9de00 (most recent call first):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/nplike.py", line 384 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/_v2/contents/numpyarray.py", line 747 in _unique
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/_v2/contents/listoffsetarray.py", line 929 in _unique
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/_v2/contents/listarray.py", line 980 in _unique
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/_v2/contents/indexedarray.py", line 725 in _unique
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/awkward/_v2/contents/content.py", line 1141 in unique
    File "/Users/runner/work/awkward-1.0/awkward-1.0/tests/v2/test_0404-array-validity-check.py", line 700 in test_IndexedArray
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
    File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp12878rgl/bin/pytest", line 8 in <module>
```

**Comment by jpivarski** [comment]
> It's a segmentation fault

Since it's MacOS, it's probably this: https://github.com/scikit-hep/awkward-1.0/issues/1209

@ianna, I'd like to hold back on releasing 1.8.0 until the segfault is fixed. Let me know when you have something. Thanks!

**Comment by henryiii** [comment]
Technically, this should be fine (the rebuild passed) - it's not worse than what was there before. #1209 should be a blocking issue, but this PR should be safe to merge.

**Pull request merged**
