### PR TITLE
Improve build procedure building from setup.py.

### PR DESCRIPTION
**Pull request by jpivarski**
Still to do:
- [x] Fix install location of python & so files (currently in .env base dir!)
- [x] Restore non-Scikit-build build (since Scikit Build 0.11 has not been released yet, and 0.10 does not support Python 0.10, see https://github.com/scikit-build/scikit-build/issues/362)

### CODE REVIEW

**Comment by jpivarski** [comment]
Some baseline compilation times on a slow (Chromebook) computer:

   * full compilation time in release mode

```
real    3m20.192s
user    3m10.504s
sys     0m12.654s
```

   * linking-only in release mode

```
real    0m52.832s
user    0m50.578s
sys     0m3.352s
```

   * full compilation in debug mode

```
real    4m49.084s
user    4m45.499s
sys     0m14.281s
```

   * linking-only in debug mode

```
real    0m8.494s
user    0m6.615s
sys     0m1.735s
```

That's an interesting trade-off.

**Comment by jpivarski** [comment]
@henryiii I've fully merged in #130 and tested it, including ArrayBuilder in Numba (which uses ctypes to access libawkward.so).

**Comment by henryiii** [comment]
Remember, we need to manually squash to 2-3 commits then rebase and merge, since we do a large renaming and several edits; if we just squash and merge git will loose the history tracking on the python files in src/awkward1. Let me know when you are ready and I can do it.

**Comment by jpivarski** [comment]
@henryiii It's ready. Please do it.

**Comment by jpivarski** [comment]
I copied this branch as [save/PR129-henryiii-build-procedure](https://github.com/scikit-hep/awkward-1.0/tree/save/PR129-henryiii-build-procedure).

**Comment by ianna** [comment]
@jpivarski and @henryiii - nice work, local builds are a lot faster! Thanks!

**Pull request merged**
