### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by reikdas**
With instructions to generate project documentation locally

### CODE REVIEW

**Comment by jpivarski** [comment]
The build command should be in a triple-backtick block to make it easier to copy paste.

It should also say you start in the top-level directory of the git repo and specify the exact directories (again, for quick copy-paste). There's no reason to suggest flexibility here: we can dictate where you call it from and where the output should go.

It should them say where the entry HTML is located, so that this path can be copied to a browser. (Relative to git top-level.)

It should also mention that doxygen is required and it will be run—some people don't have doxygen and need to get it (is that pip installable? Can it go in the dev requirements?) and anyway, people might be surprised to see doxygen running. They should at least be warned.

Users should also be warned that a lot of custom Python gets run with the Sphinx job, including some that requires a network connection. That would definitely be a surprise.

Finally, some directories are generated by this process that we sometimes want to delete to start fresh: docs-sphinx/_static, docs-sphinx/_auto, and docs-sphinx/_build or maybe _html. These should be listed, perhaps in an "rm" command that can be copy-pasted.

**Review by jpivarski — CHANGES_REQUESTED** [review]
My comment was a review.

**Comment by jpivarski** [comment]
It looks like you also need

```bash
conda install babel imagesize sphinxcontrib sphinxcontrib-serializinghtml sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-qthelp alabaster
```

Maybe a Sphinx update loosened its strict requirements and these are now "used, but not labeled as required."

And of course, there's

```bash
conda install pycparser black
```

for developers building the documentation. Alternatively, we could ask them to install `docs-sphinx/requirements.txt`, since that's where we tell ReadTheDocs to get it, and then that's all in one place.

**Comment by reikdas** [comment]
> some people don't have doxygen and need to get it (is that pip installable? Can it go in the dev requirements?)

Doxygen isn't on PyPI :( 

> It looks like you also need
> 
> ```shell
> conda install babel imagesize sphinxcontrib sphinxcontrib-serializinghtml sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-qthelp alabaster
> ```
> 
> Maybe a Sphinx update loosened its strict requirements and these are now "used, but not labeled as required."

In that case, should we also include these packages in docs-sphinx/requirements.txt? (Also I noticed that there is no package named sphinxcontrib on PyPI - must be one of those few instances conda and pip names for common packages vary)

**Comment by jpivarski** [comment]
The docs-sphinx/requirements.txt is for ReadTheDocs, which has some things preloaded, and I wouldn't want to meet that up. Setup instructions for developers can be longer than setup instructions for users. We can also expect them to get doxygen "somehow." Since this is an old, stable package, I used apt-get (being an old version didn't matter).

The "sphinxcontrib" one is the only one that might not be needed. While I was trying to satisfy requirements one at a time, I thought that might solve the "sphinxcontrib-serializinghtml" one, but it didn't. It might be some metapackage.

**Comment by jpivarski** [comment]
Great, thanks!

**Pull request merged**
