### PR TITLE
check content length before arg/sorting

### LINKED ISSUE #686: Segmentation fault from argsort and sort
```python
import awkward as ak
arr = ak.layout.IndexedArray64(ak.layout.Index64([]), ak.layout.NumpyArray([1,2,3]))
ak.argsort(arr)
```
 will exit Python with the message `Segmentation fault`.
Tested on awkward version 1.0.2 and git main.

### PR DESCRIPTION
**Pull request by ianna**
adresses https://github.com/scikit-hep/awkward-1.0/issues/686

```python
>>> import awkward as ak
>>> arr = ak.layout.IndexedArray64(ak.layout.Index64([]), ak.layout.NumpyArray([1,2,3]))
>>> ak.argsort(arr)
<Array [] type='0 * int64'>
>>> ak.sort(arr)
<Array [] type='0 * int64'>
>>> 

```

### CODE REVIEW

**Comment by jpivarski** [comment]
Thanks for the quick fix, @ianna! I'll merge this as soon as the tests pass _unless_ you tell me not to.

**Comment by ianna** [comment]
> Thanks for the quick fix, @ianna! I'll merge this as soon as the tests pass _unless_ you tell me not to.

Thanks, @jpivarski ! I'm scanning through the code to add more checks like that. I'm almost done.

**Comment by ianna** [comment]
@jpivarski - I'm done. Please merge it when the tests pass. Thanks

**Comment by jpivarski** [comment]
Can you turn @jrueb's examples into tests? I'll wait until you're done. At first, I thought this was a very simple fix, and if it's fixing a segfault, I wanted to fast-track it. The next set of updates look more involved, like this bug prompted you to search for similar bugs, and you're finding those. (If they can be expressed as tests, that, too, would be great.)

**Comment by jpivarski** [comment]
Thanks for the tests! I'll merge it as soon as these pass.

**Pull request merged**
