### PR TITLE
Adding Avro Reader for Awkward Array

### PR DESCRIPTION
**Pull request by aryan26roy**
# Things to do:
- [x] Complete the API along with debugging mode.
- [x] Rename to `metadata_from_avro_file`.
- [x] Create the test samples. (String, int, enum cover all the composite types and in addition to every leaf type by itself.)
- [x] Modify the code for reading arrays.
- [x] Write the tests for Python based reader.

### CODE REVIEW

**Comment by martindurant** [comment]
I was *not* expecting a pure python implementation! Have you seen https://github.com/martindurant/uavro ?

**Comment by jpivarski** [comment]
The pure Python implementation is a stepping-stone.

**Comment by jpivarski** [comment]
Is this an early draft of what became #1491? If so, let's close this one, since you're finished `ak.from_avro_file`.

**Comment by aryan26roy** [comment]
Yep this is the branch where I got the version with generated Python to work. Then I started a new branch from this to incorporate Forth generation. I'll close it up.

**Pull request closed without merging**
