### PR TITLE
Use `IndexedArray` instead of `carry` in ak.combinations. 

### LINKED ISSUE #204: ak.cartesian and ak.combinations should make an IndexedArray for axis > 0 as well
The `axis=0` case already does this (because arrays are long), but the other cases probably should, too, since combinatorics in the wild ends up duplicating many record fields when only a couple are desired.

In `ak.combinations`, the fix goes [right here](https://github.com/scikit-hep/awkward-1.0/blob/8215351f09de3773b14318815538ec0faaeb6235/src/libawkward/array/ListOffsetArray.cpp#L1514).

In `ak.cartesian`, it's actually in broadcasting, [right here](https://github.com/scikit-hep/awkward-1.0/blob/8215351f09de3773b14318815538ec0faaeb6235/src/awkward1/_util.py#L589-L597), and maybe `broadcast_tooffsets64` should take an option to make an IndexedArray instead of carrying ([here](https://github.com/scikit-hep/awkward-1.0/blob/8215351f09de3773b14318815538ec0faaeb6235/src/libawkward/array/ListOffsetArray.cpp#L132)) for specially chosen cases like `ak.cartesian`.

### PR DESCRIPTION
**Pull request by Ellipse0934**
As mentioned in #204

### CODE REVIEW

**Comment by jpivarski** [comment]
Thanks for looking into this!

Your solution does appear to be correct: I think all the array nodes involved in `ak.combinations` are RegularArray, ListArray, and ListOffsetArray. It is a more "local" change than the one I had been considering in https://github.com/scikit-hep/awkward-1.0/issues/204#issuecomment-611089765, which would have made every operation that rearranges a RecordArray insert an IndexedArray.

One thing, though, is that immediately after creating an IndexedArray from some operation, we must call `simplify_optiontype` on it. So instead of

```c++
contents.push_back(std::make_shared<IndexedArray64>(
        Identities::none(),
        util::Parameters(),
        Index64(ptr, 0, totallen),
        content_));
```

we want

```c++
std::shared_ptr<IndexedArray64> indexedarray =
    std::make_shared<IndexedArray64>(
        Identities::none(),
        util::Parameters(),
        Index64(ptr, 0, totallen),
        content_));
contents.push_back(indexedarray.get()->simplify_optiontype();
```

This prevents us from making IndexedArray of IndexedArray, which can get out of hand as the user composes operations.

Also, since it's an intended performance improvement, we can't take it without doing a performance test. It's intended to speed up calculations such as `In[155]` of [this notebook](https://github.com/jpivarski/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb), which combines all pairs of photons to look for those with the right mass for



decays. It was computationally expensive because it builds copies of a lot of particle records with a lot of fields, noticeable as a slight delay on my laptop and straining the ability of whatever free service Binder runs on.

Either you or I could do such a performance test, but if it's me, it will take a while to get to it. To make the computer struggle more (a better performance test, as it tests further out on the scaling curve), we could remove the requirement that the particles be photons: the `events.prt.pdg == Particle.from_string("gamma").pdgid` filter. The subsequent steps (computing the mass and filtering based on them) is still interesting, but as a part that should be timed separately.

The reason is that this is a performance _tradeoff_, rather than an absolute improvement. With `carray` instead of IndexedArray, data are copied into the combinations record. With IndexedArray instead of `carry`, a new level of indirection is placed in the combinations record, and subsequent operations must go through this layer of indirection forevermore. If the "`content_`" (above) is already something lightweight, such as NumpyArray, then it's better to `carry`, but if it's something heavyweight, like a RecordArray with lots of fields, then it's better to use IndexedArray **if** subsequent operations won't be using all of those fields. Instead of copying all the fields once, we're forevermore going through an extra layer of indirection on the fields we do use.

That's why it would be interesting to see how the speed of (1) the `ak.combinations` and (2) the subsequent mass calculation compare (a) with `carry` and (b) with IndexedArray. That would show us what this tradeoff costs in a typical case.

If the results of such a test favors IndexedArray, then we still might only do it if the `content_` is not a NumpyArray.

**Comment by Ellipse0934** [comment]
I will attempt to write the performance tests. 
What kind of testing should we do ? A couple of simple tests measuring time using `std::chrono` for a couple of different cases as mentioned above or use a tool like perf/Callgrind/GoogleBenchmark ?
This is the first issue tagged with the performance tag so I don't know what's expected.

I am a bit overwhelmed studying the internals of this package so I will take some time to complete it.

**Comment by jpivarski** [comment]
> I am a bit overwhelmed studying the internals of this package so I will take some time to complete it.

I'm pleasantly surprised that you took it on.  `:)`

The test would be at the level of Python, since the data are prepared in Python (cell 155 of the notebook I referenced above). To do so, you don't need to learn any more internals of Awkward, just to find the relevant cells for extracting and preparing the data in the form used in cell 155.

**Comment by Ellipse0934** [comment]
To evaluate the tradeoff of the original and the new implementation I did two benchmarks. The first finds the combinations of photons for the right mass as suggested above (Cell 155, [here](https://github.com/jpivarski/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb)). This is an organic example and shows the benefit so easily that I felt no need to make the test harder. 

```python
evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid][:length]

%%timeit        #TEST 1
pizero_candidates = ak.combinations(evts, 2, with_name="pair")

%%timeit       #TEST 2
pizero_candidates = ak.combinations(evts, 2, with_name="pair")
pizero = pizero_candidates[pizero_candidates.mass(0, 0) - 0.13498 < 0.000001]
pizero["px"] = pizero.slot0.px + pizero.slot1.px
pizero["py"] = pizero.slot0.py + pizero.slot1.py
pizero["pz"] = pizero.slot0.pz + pizero.slot1.pz
pizero["p"] = np.sqrt(pizero.px**2 + pizero.py**2 + pizero.pz**2)
```
|Test         |         10               |100                |1000                  |10000                   |
|------------|----------------------|------------------|---------------------|-----------------------|
|TEST 1: Original|288 µs ± 520 ns |2.93 ms ± 48.6 µs|40.7 ms ± 101 µs|409 ms ± 3.48 ms|
|TEST 1:Indexed|90.7 µs ± 122 ns |191 µs ± 273 ns|1.24 ms ± 1.15 µs|12.7 ms ± 36.7 µs|
|TEST 1:Indexed + Simplify|93.2 µs ± 275 ns|195 µs ± 322 ns|1.25 ms ± 8.17 µs|12.9 ms ± 8.39 µs|
|TEST 2: Original|11.6 ms ± 57.9 µs|20.5 ms ± 101 µs|112 ms ± 1.24 ms | 1.29 s ± 1.47 ms|
|TEST 2: Indexed|26.6 ms ± 41.8 µs |30.6 ms ± 66.8 µs|69.9 ms ± 606 µs|537 ms ± 6.35 ms|
|TEST 2: Indexed + Simplify|26.8 ms ± 234 µs|31.1 ms ± 368 µs|73.5 ms ± 979 µs|538 ms ± 6.72 ms 

The reason I have also measured the timing difference with and without `simplify_optiontype()` is that while playing around with all these versions I think I was able to create a testcase where there was a significant difference between the two versions(2x ish). I am no longer able to create such a testcase so most probably I just confused myself doing something incorrect. If you think of something that can trigger such a time difference please let me know. If there are such cases we can also consider applying `simplify_optiontype()` only when RTTI check shows `content_` is an `IndexedArray`.

Coming back to the benchmark. In the 2<sup>nd</sup> test the advantage of `carry` is demonstrated. 
```python
arr = ak.Array([[_ for _ in range(length)]])

%%timeit         #TEST 3
x = ak.combinations(arr, 2)

%%timeit         #TEST 4
x = ak.combinations(arr, 2)
ak.sum(x)
```
|Test         |         10               |100                |1000                  |10000                   |
|------------|----------------------|------------------|---------------------|-----------------------|
|TEST 3: Original|20.4 µs ± 45.3 ns|56.1 µs ± 308 ns|4.05 ms ± 40.8 µs|624 ms ± 2.71 ms
|TEST 3: Indexed|65.8 µs ± 372 ns|97.7 µs ± 114 ns|3.23 ms ± 28.9 µs|409 ms ± 2.22 ms
|TEST 3: Indexed + Simplify| 70.5 µs ± 181 ns|104 µs ± 688 ns|3.84 ms ± 27 µs|416 ms ± 2.1 ms 
|TEST 4: Original|62.1 µs ± 66.5 ns|104 µs ± 110 ns|4.73 ms ± 18.3 µs|679 ms ± 2.04 ms
|TEST 4: Indexed|197 µs ± 226 ns|289 µs ± 912 ns|9.26 ms ± 7 µs|1.35 s ± 895 µs
|TEST 4: Indexed + Simplify| 204 µs ± 706 ns|299 µs ± 3.28 µs|11.3 ms ± 194 µs|1.37 s ± 18.5 ms

I have a suggestion.
In both (original, new) implementations we are making assumptions about how the user will use `combinations` and what arguments will be passed to it potentially causing some problems. Instead of that how about passing this choice as an argument to the combinations function. For a `RecordArray` the default choice will be the new method and for `ListArray` let the default choice be the carry method. When combinations is called on a `RecordArray` the new choice is passed as a parameter to the `combinations(content_)`.

**Comment by jpivarski** [comment]
Thanks! This is helpful. Replacing `carry` with IndexedArray on a large RecordArray is a clear improvement (409 ms vs 13 ms is 40×), and the subsequent mass calculation is not negatively affected (1290 - 409 ms vs 537 - 12 ms is 1.6×, which is essentially the same, though it oddly fluctuated in favor of more indirection).

When it's pure numbers, not a large RecordArray, avoiding `carry` while calculating combinations is hardly noticeable (624 ms vs 416 ms is only 1.5×), but even a downstream calculation like "sum" is made much worse (679 - 624 ms vs 1370 - 416 ms is 17× worse).

Since we don't know how applications will use these functions, we can't optimize anything as small as a factor of 2. What's a factor of 2 better for one application will be a factor of 2 worse for another. But the 40× improvement for RecordArrays and the 17× worsening for non-RecordArrays are significant enough to affect nearly all applications and we can make decisions based on them.

It should not be a user-configurable parameter because that would blow up the complexity too much. (Giving physicists knobs to tune performance will almost surely lead to anti-tuned performance: most will use them incorrectly.) Even doing "smart" things like using IndexedArrays when the number of fields is greater than a certain number will likely lead to breaking someone's analysis in surprising ways. Whatever rule this follows, it has to follow it predictably and consistently.

Since the important thing is whether the arrays are RecordArrays, perhaps instead of changing ak.combinations, as you've done, the best thing is for `RecordArray::carry` to always generate an IndexedArray instead of carrying through to its fields. This is what I was considering here: https://github.com/scikit-hep/awkward-1.0/issues/204#issuecomment-611089765

That should have the same performance improvement as you've shown above (it would provide the gain seen in tests 1 and 2 and not affect tests 3 and 4). I'm just not sure if it will crash: until now, I've always assumed that the return value of `carry` has the same type as the input. I don't know what will happen if `RecordArray::carry` can return an `IndexedArray`. (Note: it doesn't have to simplify because such a step cannot create IndexedArray of IndexedArray.)

**Comment by Ellipse0934** [comment]
I'm not sure that I understand the last two paragraphs above. Right now when combinations is called on `RecordArrays` ([here](https://github.com/scikit-hep/awkward-1.0/blob/master/src/libawkward/array/RecordArray.cpp#L946)). It calls combinations on all its `content`. Hence, there is no `RecordArray::carry` called in this function.

Which shows a flaw in this implementation. Since all the fields have the same structure it's quite wasteful to regenerate the combinations mask every single time (Unless the overhead of computing this is very less which I have not measured).  We should generate this mask in the local scope of `combinations(RecordArray)` and then change all internal Arrays to indexed arrays.

We will revert the changes here back to the original `carry` implementation.

**Comment by jpivarski** [comment]
> I'm not sure that I understand the last two paragraphs above. Right now when combinations is called on `RecordArrays` ([here](https://github.com/scikit-hep/awkward-1.0/blob/master/src/libawkward/array/RecordArray.cpp#L946)). It calls combinations on all its `content`. Hence, there is no `RecordArray::carry` called in this function.

Actually, no, if program flow enters the `RecordArray::combinations` method, then we're not computing combinations on this level. If each field of a record is a simple number, then we're not computing them on that level, either (`depth` counts list depth, not RecordArray or IndexedArray depth) and that would just be a user error (no calculation performed). The only way that program flow could descend into each of those fields in `contents_` and not end up raising an error is if each of the fields contains a list, and then we should compute them separately because each of those lists could have different lengths. We need to compute all the fields separately because they can and usually will produce different results.

What I was actually talking about was replacing RecordArray's `carry` implementation, which eagerly rearranges every field:

https://github.com/Ellipse0934/awkward-1.0/blob/2b243ef8abbb8abf80628633f5d5a4dcaa9437d8/src/libawkward/array/RecordArray.cpp#L439-L454

with an implementation that instead just returns an IndexedArray of that RecordArray, lazily rearranging every field. In other words,

```c++
  const ContentPtr
  RecordArray::carry(const Index64& carry) const {
    IdentitiesPtr identities(nullptr);
    if (identities_.get() != nullptr) {
      identities = identities_.get()->getitem_carry_64(carry);
    }
    return std::make_shared<IndexedArray64>(identities,
                                            Parameters::none(),
                                            carry,
                                            shallow_copy());
  }
```

instead of replacing the _call_ to `carry` in `ListArray::combinations`, `ListOffsetArray::combinations`, and `RegularArray::combinations`. That should make the general situation like your test 2 (RecordArrays are lazily rearranged by `combinations`) and your test 3 (non-RecordArrays are eagerly rearranged by `combinations`), the best of both worlds, by factors of 40×and 20×.

It would do a lot of other things as well, and I'm not 100% sure that the result will be error-free. But assuming that it's error-free or the errors can be fixed, it might be the best policy, not just for `combinations`, but for all operations.

**Comment by Ellipse0934** [comment]
I think I understood some of what I misunderstood. The first being how a `RecordArray` is structured, and the other which I have still not quite understood.

How is `RecordArray::carry` called from `RecordArray::combinations(...)`. If `axis = 0` then `combinations_axis0` is called which does not call it, otherwise for all  `content[i].type::combinations` is called which only calls carry on its own type and not the parent. But definitely it's being called because the behavior changed when I copy pasted the code you wrote above.

On my machine rerunning the benchmark for length  1000: 
- TEST 1:  1.91 ms
- TEST 2:  65.3 ms
- TEST 3:  5.95 ms
- TEST 4: 6.67 ms

These results are as you predicted are the best of both cases.
However some test crashed from a segmentation fault and there are some weird artifacts which I cannot understand. 

So, right now either you can accept the current PR or close it and later this topic should be revisited. I think I'll work on the `is_none()` now as it seems within my reach.

**Comment by jpivarski** [comment]
I half-expected segfaults when replacing RecordArray's `carry` implementation with an IndexedArray. Until now, I'd always assumed that the type that the type of `xyz.get()->carry()` is equal to the type of `xyz`, and this change breaks that assumption. I'll have to carefully review all the uses of carried data to see where the assumption is being relied upon.

Thanks for trying it! (There was a chance it could have gone without any errors.)

**Comment by Ellipse0934** [comment]
Closing PR as it seems like we may have a better implementation in the future. 
As it is I dislike the PR in its current state.

**Pull request closed without merging**
