### PR TITLE
fix: pass memo to deepcopy

### PR DESCRIPTION
**Pull request by agoose77**
@jpivarski whoops, somehow I missed this on your PR.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
Right—I can't think of a legitimate case in which an ak.Array instance is inside of the `behavior` dict, but this is formally correct and if such a situation does show up in the future, this implementation fixes a potential bug.

I'm setting up auto-merge.

**Comment by agoose77** [comment]
NB - this PR is now placing more importance on `behavior` being None if the user wants `ak.behavior` - now we deepcopy this, which would be expensive if we are currently passing around `ak.behavior` explicitly.

**Comment by jpivarski** [comment]
Presumably, if someone actually says

```python
my_new_array = copy.deepcopy(my_awk_array)
```

then they don't want `my_new_array` to share data with `my_awk_array`.

**But**, behaviors contain class objects and functions. We don't want them to be copied.

```python
>>> import copy
>>> def some_function(x): return x
... 
>>> class SomeClass: pass
... 
>>> behavior = {"function": some_function, "class": SomeClass, some_function: "as key"}
>>> copied_behavior = copy.deepcopy(behavior)
>>> behavior["function"] is copied_behavior["function"]
True
>>> behavior["class"] is copied_behavior["class"]
True
>>> list(behavior.keys())[2]
<function some_function at 0x1057c7e20>
>>> list(behavior.keys())[2] is list(copied_behavior.keys())[2]
True
```

Okay: they're not.

**Comment by agoose77** [comment]
> Okay: they're not.

Yes, right now this would only be an issue if a user is passing an instance _method_ (or other non-atomically copied value) into `ak.behavior`, e.g.

```python
class SpecialAdder:
    def add(self, x, y):
        ...

ak.behavior[np.add, "point", "point"] = SpecialAdder().add
```

Whilst I don't anticipate this, I think it's worth discussing it up-front in case we this these kinds of issues later.

**Pull request merged**
