### PR TITLE
Write a type parser for TypedArrayBuilder

### PR DESCRIPTION
**Pull request by reikdas**

### CODE REVIEW

**Comment by jpivarski** [comment]
This is good; doing it in `studies` for now.

**Review by jpivarski — COMMENTED** [review]
I checked it out and tried some examples. Some of these didn't work, so I labeled them as `pytest.mark.skip`, but that makes them visible when you run

```bash
pytest -vv -rs parser.py
```

At least check to see how difficult it would be to add these. (I want to be sure that the structure of the parser will accommodate them.) Thanks!

**Comment by reikdas** [comment]
@jpivarski All the tests you added pass now. Should we merge this into `studies/` now and then create a separate PR where we integrate it into the main codebase?

**Comment by jpivarski** [comment]
> @jpivarski All the tests you added pass now. Should we merge this into `studies/` now and then create a separate PR where we integrate it into the main codebase?

Yes! You can merge it whenever you're ready.

**Pull request merged**
