### PR TITLE
fix: handle type tracer correctly in indexed option array flattening

### LINKED ISSUE #3324: flattening of indexed option typetracer array causes comparison of unknown length to known length
### Version of Awkward Array

2.6.9

### Description and code to reproduce

c.f. https://github.com/scikit-hep/coffea/issues/1199 for reproducer

Summary:
The code path for the typetracer hits:
```
File ~/mambaforge/envs/python311/lib/python3.11/site-packages/awkward/contents/indexedoptionarray.py:595, in IndexedOptionArray._offsets_and_flattened(self, axis, depth)
    591 next = self._content._carry(nextcarry, False)
    593 offsets, flattened = next._offsets_and_flattened(axis, depth)
--> 595 if offsets.length == 0:
    596     return (
    597         offsets,
    598         ak.contents.IndexedOptionArray(
    599             outindex, flattened, parameters=self._parameters
    600         ),
    601     )
    603 else:
```

This code path still exists in 2.7.1 / latest:
https://github.com/scikit-hep/awkward/blob/main/src/awkward/contents/indexedoptionarray.py#L603-L637

Probably just needs a ```offsets.length is not unknown_length and ...``` added in to handle the typetracer.

### PR DESCRIPTION
**Pull request by lgray**
Fixes #3324

@pfackeldey if my little patch breaks things please give it a try. I'll try to cook up a test in the mean time.

### CODE REVIEW

**Comment by lgray** [comment]
@jpivarski @pfackeldey this is now ready to go! the fix was that simple.

**Review by jpivarski — APPROVED** [review]
LGTM!

**Review by jpivarski — APPROVED** [review]

**Comment by jpivarski** [comment]
I think that GitHub Actions is having problems right now.

**Comment by lgray** [comment]
macos-12 images were sunset.

**Comment by lgray** [comment]
or was it supposed to automerge it?

**Pull request merged**
