### PR TITLE
fix: requesting layout.form should not touch shape

### PR DESCRIPTION
**Pull request by jpivarski**
@martindurant

### CODE REVIEW

**Comment by martindurant** [comment]
Is awkward main still compatible with the last awkward-cpp, so that I can install this simply without recompiling?

**Comment by martindurant** [comment]
I was also going to comment "wow, so many lines", but I see it's all tests for the different classes.

**Comment by jpivarski** [comment]
> Is awkward main still compatible with the last awkward-cpp, so that I can install this simply without recompiling?

I think so. I'm testing against `main` here: https://github.com/scikit-hep/awkward/actions/runs/10163112284

And testing against `pivarski/requesting_form_should_not_touch_shape` here: https://github.com/scikit-hep/awkward/actions/runs/10163115961

Oh, apparently not. Let me see if I can get a new awkward-cpp into PyPI today.

**Comment by jpivarski** [comment]
A new version of awkward-cpp is available. You can just pip-install it.

**Comment by martindurant** [comment]
This seems to work as intended.
I still don't know how to solve the concat case, though - we can talk about that separately.

**Comment by agoose77** [comment]
I like this! It makes sense that we don't need any shape-_content_ information to know that the inner_shape is `()` -- the dimension is a form-level thing.

**Pull request merged**
