### PR TITLE
feat: Implement Indexed builder

### PR DESCRIPTION
**Pull request by zonca**
As discussed with @jpivarski and @ManasviGoyal, here is the implementation of the Indexed layout builder.
The final objective is to use this for `EnumType` instead of using `NumpyBuilder`.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
I approved this on zonca/awkward#3, and see that it's the same `Indexed` Builder implementation here.

This doesn't have the

```diff
- cmake -B build -S header-only -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
+ cmake -B build -S header-only -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
```

update in .github/workflows/header-only-test.yml, but that's unrelated to adding the new Builder, so it's best not to have it in the PR, anyway. Everything else looks goo. (The zonca/awkward#3 was a difference after `IndexedOption` had been copied to `Indexed`, but this is a more direct addition.)

I'll merge it when the tests pass.

**Comment by jpivarski** [comment]
We only need one approval for merging. Last time, @ManasviGoyal also approved it, anyway.

**Comment by zonca** [comment]
> I approved this on [zonca#3](https://github.com/zonca/awkward/pull/3), and see that it's the same `Indexed` Builder implementation here.
> 
> This doesn't have the
> 
> ```diff
> - cmake -B build -S header-only -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
> + cmake -B build -S header-only -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
> ```
> 
> update in .github/workflows/header-only-test.yml, but that's unrelated to adding the new Builder, so it's best not to have it in the PR, anyway. Everything else looks goo. (The [zonca#3](https://github.com/zonca/awkward/pull/3) was a difference after `IndexedOption` had been copied to `Indexed`, but this is a more direct addition.)

right, that was already merged back in https://github.com/scikit-hep/awkward/pull/2870

**Comment by jpivarski** [comment]
@all-contributors please add @zonca for code

**Pull request merged**
