### PR TITLE
ci: deploy branch preview docs only on main repo

### PR DESCRIPTION
**Pull request by zonca**
Forked repositories normally do not have secrets correctly configured,
so the deploy preview of the docs always fail, making PRs on forks always failing.
Of course this won't work if you have cases where you have forked repos with secrets.

See
https://github.com/orgs/community/discussions/26409#discussioncomment-3251822

### CODE REVIEW

**Comment by zonca** [comment]
apologies just noticed there was already a `if` statement on that action,
however it does not seem to work:

https://github.com/zonca/awkward/pull/6

**Comment by zonca** [comment]
hopefully this one instead is working:

https://github.com/zonca/awkward/pull/7

**Comment by agoose77** [comment]
We need to think about this - we don't want to leak any secrets to forked PRs. When I looked last, I felt we couldn't use any of the mechanisms for opening permissions without compromising access keys. It might be somewhat viable, I'll take a look this week!

**Comment by agoose77** [comment]
Thanks for this PR! I'm going to close it, because there are security concerns with deploying docs from third-party repositories; we don't have any way of ensuring that executable code run during the docs is well-behaved, or that the built assets that are deployed aren't e.g. embedding a cryptominer. 

The only way I think we can implement this securely (without requiring people to constantly be vigilant) is to implement a one-off execution for a fork. I don't think there's a convenient way to do that, unfortunately.

**Pull request closed without merging**
