### PR TITLE
chore: Ruff updates from dev guidelines (#2268)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com> Co-authored-by: Jim Pivarski <jpivarski@users.noreply.github.com>

### PR DESCRIPTION
**Pull request by henryiii**
Some updates for a better experience and more checks.

There are several more that would be nice to activate:

* NPY: I've had to disable one of the checks here for deprecated usage of np.random
* PD: We aren't using Pandas in an idiomatic way, it seems (or it might just be false positives - Ruff may add a nice way to select just a subset of files soon)
* SIM: Some nice simplifications, but needs to be it's own PR
* PT: Some nice pytest simplifications (though not every rule is good), needs to be it's own PR
* RET: Best in it's own PR, removes unused returns

### CODE REVIEW

**Comment by jpivarski** [comment]
> * NPY: I've had to disable one of the checks here for deprecated usage of np.random

Odd; there are no uses of `np.random` in the codebase; it appears in a few _docstrings_ in highlevel.py, and there are some uses in tests/*.py.

With NumPy 1.23.5, I'm not seeing deprecation warnings (even for the usage patterns in docstrings). Maybe they're more recent deprecations?

> * PD: We aren't using Pandas in an idiomatic way, it seams

The only file that uses Pandas is `ak_to_dataframe.py`, which probably isn't idiomatic Pandas use because it has to construct a DataFrame from an Awkward Array in general.

**Comment by henryiii** [comment]
NumPy issues are only in tests:

```
tests/test_1030_mixin_class_name.py:19:9: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1030_mixin_class_name.py:20:9: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1125_to_arrow_from_arrow.py:193:9: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1125_to_arrow_from_arrow.py:201:25: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1125_to_arrow_from_arrow.py:203:13: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1294_to_and_from_parquet.py:227:9: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1294_to_and_from_parquet.py:238:25: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1294_to_and_from_parquet.py:240:13: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1440_start_v2_to_parquet.py:172:9: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1440_start_v2_to_parquet.py:178:25: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
tests/test_1440_start_v2_to_parquet.py:180:13: NPY002 Replace legacy `np.random.randint` call with `np.random.Generator`
Found 11 errors.
```

So very low priority, but still might be nice to have proper examples of how to use modern NumPy if anyone happens along. Pretty sure they won't kill it off, it's just labeled "Legacy" at the moment.

Pandas is giving some false positives, actually:

```
src/awkward/_broadcasting.py:557:26: PD013 `.melt` is preferred to `.stack`; provides same functionality
src/awkward/_connect/numba/arrayview.py:458:5: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/_connect/numba/arrayview.py:519:9: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/_connect/numba/arrayview.py:569:5: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/_connect/numba/arrayview.py:585:5: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/_connect/numba/layout.py:1193:13: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/_nplikes/array_module.py:228:16: PD013 `.melt` is preferred to `.stack`; provides same functionality
src/awkward/behaviors/categorical.py:21:9: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:31:17: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:31:32: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:37:9: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:38:43: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:44:53: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/behaviors/categorical.py:44:68: PD011 Use `.to_numpy()` instead of `.values`
src/awkward/contents/unionarray.py:1500:23: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/highlevel.py:2061:59: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_fill_none.py:101:45: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_fill_none.py:101:62: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_arrow.py:103:31: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_arrow.py:103:43: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_arrow_table.py:106:31: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_arrow_table.py:106:43: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_dataframe.py:216:32: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_dataframe.py:216:44: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_json.py:164:34: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_json.py:164:52: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_json.py:170:27: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
src/awkward/operations/ak_to_json.py:170:38: PD008 Use `.loc` instead of `.at`.  If speed is important, use numpy.
tests/test_0331_pandas_indexedarray.py:15:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:28:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:38:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:49:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:59:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:69:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:81:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:89:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:95:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:104:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:114:5: PD901 `df` is a bad variable name. Be kinder to your future self.
tests/test_0331_pandas_indexedarray.py:115:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0331_pandas_indexedarray.py:116:12: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0835_datetime_type_pandas.py:15:5: PD901 `df` is a bad variable name. Be kinder to your future self.
tests/test_0835_datetime_type_pandas.py:18:30: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0835_datetime_type_pandas.py:20:31: PD011 Use `.to_numpy()` instead of `.values`
tests/test_0875_arrow_null_type.py:33:17: PD012 `.read_csv` is preferred to `.read_table`; provides same functionality
tests/test_1125_to_arrow_from_arrow.py:38:13: PD012 `.read_csv` is preferred to `.read_table`; provides same functionality
tests/test_2202_filter_multiple_columns_from_rdataframe.py:27:5: PD901 `df` is a bad variable name. Be kinder to your future self.
tests/test_2202_filter_multiple_columns_from_rdataframe.py:33:5: PD901 `df` is a bad variable name. Be kinder to your future self.
tests/test_2234_from_rdataframe_keep_order.py:119:5: PD901 `df` is a bad variable name. Be kinder to your future self.
tests/test_2234_from_rdataframe_keep_order.py:125:5: PD901 `df` is a bad variable name. Be kinder to your future self.
```

It's not being smart about making sure the objects really are Pandas objects. I think Ruff can be a bit smarter about this, so it's likely just a direct port of the flake8 tool without extra logic for tracking the objects. (It's can't fully do it without types, though, and I think Ruff is working on replacing Black before it works on replacing mypy :D )

**Comment by henryiii** [comment]
Okay to have this go in? I can start working on enabling a few of these in a followup.

**Comment by jpivarski** [comment]
If the Build Docs test passes this time, then yes, I think this is okay to go in. It doesn't look like it will interfere with any other open PRs.

**Comment by henryiii** [comment]
Is pydata_sphinx_theme broken, perhaps? It had a 0.13 release 12 hours ago.

**Comment by jpivarski** [comment]
That's what I was thinking, so I tested `main` and a few other branches: https://github.com/scikit-hep/awkward/actions/workflows/docs.yml

They all fail the same way.

We could put a temporary upper limit on pydata_sphinx_theme or wait and see if it gets resolved.

https://github.com/pydata/pydata-sphinx-theme/issues/1149 seems relevant.

Meanwhile, _this_ PR looks okay. The docs won't get updated until this gets fixed, but this PR doesn't change anything in the docs. I'll merge this and make an issue for the docs.

**Comment by agoose77** [comment]
Following Jim's comments, I'll force merge this.

**Pull request merged**
