### PR TITLE
Fix: add utility to check whether a string is a filepath

### LINKED ISSUE #1084: "path too long for Windows" when calling `ak.from_json` with a long json string on Windows
### Version of Awkward Array

not sure

### Description and code to reproduce

Discovered by a student in a course (who was working on Windows). We were going through the bikeroutes example:

```python
import awkward as ak
import urllib
url = "https://raw.githubusercontent.com/Chicago/osd-bike-routes/master/data/Bikeroutes.geojson"
bikeroutes_json = urllib.request.urlopen(url).read()
bikeroutes = ak.from_json(bikeroutes_json)
```

Gave him the following error:

```
ValueError Traceback (most recent call last)
<ipython-input-25-171b38169686> in <module>
----> 1 bikeroutes = ak.from_json(bikeroutes_json)

~\Anaconda3\lib\site-packages\awkward\operations\convert.py in from_json(source, nan_string, infinity_string, minus_infinity_string, complex_record_fields, highlevel, behavior, initial, resize, buffersize)
1054 is_path, source = ak._util.regularize_path(source)
1055
-> 1056 if os.path.isfile(source):
1057 layout = ak._ext.fromjsonfile(
1058 source,

~\Anaconda3\lib\genericpath.py in isfile(path)
28 """Test whether a path is a regular file"""
29 try:
---> 30 st = os.stat(path)
31 except OSError:
32 return False

ValueError: stat: path too long for Windows
```

unfortunately i currently have no windows Installation available to reproduce it

### PR DESCRIPTION
**Pull request by agoose77**
I didn't follow the `isint` / `isstr` convention: I think we should rename those in a subsequent PR

### CODE REVIEW

**Comment by agoose77** [comment]
This might fix #1084 (but we need to add a test)

**Comment by jpivarski** [comment]
There's an `ak._util.iswin` to check to see if you're on Windows and we know that the bikeroutes JSON is too long to be a Windows path. Such a test would require an HTTP connection, which should probably skip if the attempt to download with

```python
import urllib.request

url = "https://raw.githubusercontent.com/Chicago/osd-bike-routes/master/data/Bikeroutes.geojson"
bikeroutes_json = urllib.request.urlopen(url).read()
```

fails.

**Comment by agoose77** [comment]
> There's an `ak._util.iswin` to check to see if you're on Windows and we know that the bikeroutes JSON is too long to be a Windows path. Such a test would require an HTTP connection, which should probably skip if the attempt to download with
> 
> ```python
> import urllib.request
> 
> url = "https://raw.githubusercontent.com/Chicago/osd-bike-routes/master/data/Bikeroutes.geojson"
> bikeroutes_json = urllib.request.urlopen(url).read()
> ```
> 
> fails.

Let's use that instead — it's a more direct test.

**Comment by jpivarski** [comment]
I didn't merge this because (as I understand it), it's waiting for a test. If I should add it to 1.5.0, let me know. Otherwise, there will probably be only one release candidate before the final release (but technically two "rc" releases in GitHub because it looks like the first one didn't trigger).

**Comment by jpivarski** [comment]
Nope; that's because Azure isn't configured to deploy anymore—it's handled by GitHub Actions now, and I had forgotten.

**Comment by jpivarski** [comment]
Oh, I was thinking that this could just be a test that attempts to download through HTTP, and skips if it fails. I don't think it would be the only test that requires network access.

That way, we don't need to add a copyright message for Chicago's data. We're really just wanting it for its size (which could also be an auto-generated JSON, if we really want to avoid network access).

**Comment by agoose77** [comment]
I've added a test, but I can't test the previous behaviour against this test unless I poke around with the CI. Do you happen to have a Windows machine to hand?

**Comment by agoose77** [comment]
> I've added a test, but I can't test the previous behaviour against this test unless I poke around with the CI. Do you happen to have a Windows machine to hand?



> Oh, I was thinking that this could just be a test that attempts to download through HTTP, and skips if it fails. I don't think it would be the only test that requires network access.
> 
> That way, we don't need to add a copyright message for Chicago's data. We're really just wanting it for its size (which could also be an auto-generated JSON, if we really want to avoid network access).

Right, I forgot to motivate why I downloaded a sample; the data are quite large. It's not a *slow* download, but it's enough that I don't think we want to add it to the test suite unless required. Are you not comfortable with including the license file? It's not infectious, and it's only in the test suite.

**Comment by jpivarski** [comment]
> Do you happen to have a Windows machine to hand?

The CI is our only access (both of us).

> Right, I forgot to motivate why I downloaded a sample; the data are quite large. It's not a slow download, but it's enough that I don't think we want to add it to the test suite unless required.

I considered it small enough to use in a classroom setting, and the downloads in CI are a lot faster than they are at home. (The CI machines are well-connected!) I just downloaded it in 0.3 seconds at home.

Generating simple JSON that is as large as the bikeroutes file would be sufficient. The bikeroutes sample is 2.3 MB, and a list of numbers up to 1 million is 7.8 MB:

```python
json.dumps(np.arange(1000000).tolist())
```

Generating it and interpreting it as an Awkward Array takes 0.2 seconds:

```python
ak.Array(json.dumps(np.arange(1000000).tolist()))
```

Without your fix, the above line should fail in Windows (CI).

**Comment by agoose77** [comment]
If we want to test the Windows case, then we only need 260 chars of JSON, although I can see the merit in re-using a "large" dataset. I will update with your suggestions.

**Comment by jpivarski** [comment]
Oh yeah, and although the license is not infectious, simplifying things to the extent that no one has to evaluate whether that is the case is beneficial. I have a bias against including anything that requires a license, which can be overcome by a good enough reason: Lark has a good enough reason, as does pybind11, as well as RapidJSON... I just want to keep the list short, and this one test is doable without having to add the dataset.

**Comment by jpivarski** [comment]
> 260 chars of JSON

I didn't know the threshold, but I did know that the bikeroutes exceeded it. That's the thinking behind the 7 MB of JSON.

**Comment by agoose77** [comment]
Oh, I ignored py2 here because I was thinking about v2. However, it makes sense to merge this now - thanks for backporting it

**Pull request merged**
