### PR TITLE
feat: expose simplification from `ak.from_buffers`

### PR DESCRIPTION
**Pull request by agoose77**
This PR supersedes #2700 in simplify adding a new `allow_noncanonical_form` argument to `from_buffers`. This is a much more concise API change.

### CODE REVIEW

**Comment by agoose77** [comment]
@danielballan this PR should do it! Apologies, this slipped off my task list.

**Comment by agoose77** [comment]
I've employed a rule that if `from_buffers` has a known length, then the buffer itself must have a known length. This means that placeholders inside unions would be required to have known lengths.

The purpose of imposing this constraint that `from_buffers` can be naive, and as such render the caller of `from_buffers` responsible for populating the lengths appropriately. However, I this might be that this is too restrictive, and perhaps we should just let `from_buffers` fill in unknown lengths when it has the ability to. In any case, such a change could be made at a later date.

**Review by jpivarski — APPROVED** [review]
In our conversations about what would be a good API, this is where we settled. I like the name and think that an argument on the single function is the best way to do it.

**Comment by jpivarski** [comment]
> I've employed a rule that if `from_buffers` has a known length, then the buffer itself must have a known length. This means that placeholders inside unions would be required to have known lengths.

:heavy_check_mark:

I can imagine wanting to be selective about which fields of a record one reads, but not about which possibilities of a union array. Possibilities in a union are supposed to be a short list; records can have thousands of fields.

**Comment by jpivarski** [comment]
I think this is ready to merge. (The code change is rather small; it's mostly an extensive test.)

**Comment by danielballan** [comment]
Thanks to you both!

**Pull request merged**
